apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: kafka-message-queue-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: longhorn-local-ext4-1replica
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false    
         
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: kafka-message-queue-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: longhorn-network-xfs-1replica # xfs optimized for sequential writes; suboptimal: network mounted storage adds latency;
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false

