apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - kafka-pool.yaml

# namespace: kafka-message-queue # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: kafka-message-queue
    unsetOnly: true
