# creates a user with password for Kafka clients
# example - https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/security/scram-sha-512-auth/user.yaml

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user
  labels:
    strimzi.io/cluster: kafka-message-queue-cluster
spec:
  authentication:
    type: scram-sha-512

  # needs to be enabled in Kafka CR spec.kafka.authorization
  # authorization:
  #   type: simple

  #   #   # https://strimzi.io/docs/operators/latest/configuring.html#type-AclRule-schema-reference
  #   acls:
  #     - resource:
  #         type: topic
  #         name: "*"
  #         patternType: literal
  #       type: allow
  #       operations:
  #         - All
  #       host: "*"

  #     - resource:
  #         type: group
  #         name: "*"
  #         patternType: literal
  #       type: allow
  #       operations:
  #         - All
  #       host: "*"

  #     - resource:
  #         type: cluster
  #       type: allow
  #       operations:
  #         - All
  #       host: "*"

  #     - resource:
  #         type: transactionalId
  #         name: "*"
  #         patternType: literal
  #       type: allow
  #       operations:
  #         - All
  #       host: "*"
