# fixes service name association for resource (https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#builtin-namereference)

# NOTE: the condition for this to apply requires targets to be in the same namespace 
# Patch to associate backend reference of HTTPRoute rule with Service name
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: Cluster
        path: spec/bootstrap/initdb/postInitApplicationSQLRefs/configMapRefs/name
        version: v1
        group: postgresql.cnpg.io
