apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: pgadmin4

requires:
  - path: .
    configs: [pgadmin4-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: pgadmin4-generic

deploy:
  helm: {}
  kubectl: {}
  statusCheck: true

portForward:
  - resourceType: Service
    namespace: default
    resourceName: pgadmin4
    port: 80

profiles:

- name: development

  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  
  deploy: 
    helm:
      releases:
        - name: pgadmin4
          remoteChart: runix/pgadmin4
          namespace: default
          createNamespace: true
          valuesFiles:
            - pgadmin4-values.yaml

      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@pgadmin4 development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@pgadmin4 development"]
              dir: .


- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod

  deploy: 
    helm:
      releases:
        - name: pgadmin4
          remoteChart: runix/pgadmin4
          namespace: default
          createNamespace: true
          valuesFiles:
            - pgadmin4-values.yaml

      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@pgadmin4 production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@pgadmin4 production"]
              dir: .
        