apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auth-ory-stack

requires:
  - path: k8s
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ./ory-kratos
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ./ory-hydra
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ./ory-keto
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ./ory-oathkeeper
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]
