apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auth-ory-stack

deploy:
  kubectl: {}
  statusCheck: true

profiles:

- name: development
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@auth-ory-stack development"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@auth-ory-stack development"]
              dir: .

- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@auth-ory-stack production"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@auth-ory-stack production"]
              dir: .