apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auth-ory-stack

requires:
  - path: .
    configs: [auth-ory-stack-generic]

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auth-ory-stack-k8s

deploy:
  kubectl: {}
  statusCheck: true

profiles:

- name: development
  manifests:
    kustomize:
      paths:
      - ./k8s/overlays/dev
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@auth-ory-stack development"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@auth-ory-stack development"]
              dir: .

- name: production
  manifests:
    kustomize:
      paths:
      - ./k8s/overlays/prod
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@auth-ory-stack production"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@auth-ory-stack production"]
              dir: .

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auth-ory-stack-generic

requires:
  - path: .
    configs: [auth-ory-stack-k8s]                 
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production
        activatedBy: [production]

  - path: ./ory-kratos
    configs: [ory-kratos]

  - path: ./ory-hydra
    configs: [ory-hydra]                 

  - path: ./ory-keto
    configs: [ory-keto]                 

  - path: ./ory-oathkeeper
    configs: [ory-oathkeeper]

profiles:
  - name: development
  - name: local-production
  - name: production

