# helm values
# https://k8s.ory.sh/helm/hydra.html
# https://github.com/ory/k8s/blob/master/helm/charts/hydra/values.yaml

hydra:
  # dangerousForceHttp: true

  automigration:
    enabled: true

  maester:
    enabled: true # enabled by default
