# yaml config options passed to Kratos
# https://www.ory.sh/docs/kratos/reference/configuration

kratos:
  config:
    # NOTE: use for debug only
    # dev: true
    # log:
    #   level: debug
    #   format: text
    #   leak_sensitive_values: true

    # dsn: memory # NOTE: use for development only
    dsn: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres-kratos-postgresql:5432/kratos_db?sslmode=disable"

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json

    serve:
      # links to generete for kratos-public internal server
      public:
        base_url: "https://auth.wosoom.com/authenticate"
        cors:
          enabled: true
          allowed_origins:
            # - "*" # NOTE: use for debug only
            - https://auth.wosoom.com/
            - https://wosoom.com/
            - https://*.wosoom.com/
          allowed_methods:
            - GET
            - OPTIONS
            - PUT
            - PATCH
            - DELETE
      admin:
        base_url: http://kratos-admin:80/

    selfservice:
      methods:
        password: # email/password authentication
          enabled: true # default enabled
        totp: # MFA
          config:
            issuer: donation-app
          enabled: true
        lookup_secret: # backup codes for 2FA
          enabled: true
        link: # one-time link authentication
          enabled: true
        code: # one-time code authentication
          enabled: true

      # links to generate for kratos ui pages
      default_browser_return_url: https://auth.wosoom.com/
      allowed_return_urls:
        - https://wosoom.com/
        - https://auth.wosoom.com/
        - https://*.wosoom.com/

      flows:
        login:
          ui_url: https://auth.wosoom.com/login
          lifespan: 10m
        logout:
          after:
            default_browser_return_url: http://auth.wosoom.com/login
        verification:
          enabled: true
          ui_url: https://auth.wosoom.com/verification
          # use: code
          after:
            default_browser_return_url: http://wosoom.com/
        registration:
          ui_url: https://auth.wosoom.com/registration
          lifespan: 10m
          after:
            password:
              hooks:
                - hook: session
                # - hook: show_verification_ui
        settings:
          ui_url: https://auth.wosoom.com/settings
          privileged_session_max_age: 15m
          # required_aal: highest_available
        recovery:
          enabled: true
          ui_url: http://auth.wosoom.com/recovery
          # use: code
        error:
          ui_url: https://auth.wosoom.com/error

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true # TODO: update with deployed one

    secrets:
      default:
        - should-be-autogenerated-and-replaced # replaced with helm command argument
      cookie:
        - should-be-autogenerated-and-replaced # replaced with helm command argument
      cipher:
        - should-be-autogenerated-and-replaced # replaced with helm command argument

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    cookies:
      domain: ".wosoom.com" # allow cookie for root and subdomains
      path: "/"
      same_site: Strict

    # emailTemplates: {}

    feature_flags:
      use_continue_with_transitions: true # allow flexible flows (e.g. agree on terms in the registration flow, etc.)
