# yaml config options passed to Kratos
# https://www.ory.sh/docs/kratos/reference/configuration

kratos:
  config:
    # TODO: production
    log:
      level: debug
      format: text
      leak_sensitive_values: true

    # TODO: production
    dsn: memory
    # dsn: postgresql://kratos:kratos@postgress.donation-app.svc.cluster.local:5432/kratos-db

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json

    selfservice:
      default_browser_return_url: https://auth.wosoom.com/welcome

      flows:
        error:
          ui_url: https://auth.wosoom.com/error
        login:
          ui_url: https://auth.wosoom.com/login
        verification:
          enabled: false
          ui_url: https://auth.wosoom.com/verification
        registration:
          ui_url: https://auth.wosoom.com/registration
        settings:
          ui_url: https://auth.wosoom.com/settings

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true # TODO: update with deployed one

    secrets:
      default:
        - should-be-autogenerated-and-replaced # replaced with helm command argument
      cookie:
        - should-be-autogenerated-and-replaced # replaced with helm command argument
      cipher:
        - should-be-autogenerated-and-replaced # replaced with helm command argument

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    cookies:
      domain: ".wosoom.com" # allow cookie for root and subdomains
      path: "/"
      same_site: Strict
      secure: true

    # emailTemplates: {}
