apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

  - ../../../../service/cilium-gateway/k8s/overlays/prod
  - ../../../../service/envoy-proxy/k8s/base
  
  # - ../../../../service/auth-ory-stack/k8s/overlays/prod
  # - ../../../../service/auth-ory-admin-ui/k8s/overlays/prod
  # - ../../../../service/auth-token-exchange/k8s/overlays/prod
  # - ../../../../service/auth-ui/k8s/overlays/prod
  
  # - ../../../../service/web-server/k8s/overlays/prod
  # - ../../../../service/api-data/server/k8s/overlays/prod

  - ../../route
  
# namePrefix: prod-
# nameSuffix: -v1

configurations:
  - ./name-reference.kustomize-config.yml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: "worker"

  ###
  - target:
      kind: HTTPRoute
      name: https-test
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "test.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-test
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "test.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-test-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "test.wosoom.com"

  ###
  - target:
      kind: HTTPRoute
      name: https-api
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "api.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-api
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "api.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-api-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "api.wosoom.com"
  ###
  - target:
      kind: HTTPRoute
      name: https-k8s-longhorn
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "longhorn.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-k8s-longhorn
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "longhorn.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-k8s-longhorn-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "longhorn.k8s.wosoom.com"
  ###
  - target:
      kind: HTTPRoute
      name: https-k8s-dashboard
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "dashboard.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-k8s-dashboard
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "dashboard.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-k8s-dashboard-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "dashboard.k8s.wosoom.com"
  ###
  - target:
      kind: HTTPRoute
      name: https-k8s-hubble
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "hubble.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-k8s-hubble
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "hubble.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-k8s-hubble-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "hubble.k8s.wosoom.com"
