apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ory-kratos-db

requires:
  - path: .
    configs: [ory-kratos-db-generic]
    activeProfiles:
      - name: dev-env
        activatedBy: [dev-watch, dev-rebuild]
      - name: staging-env
        activatedBy: [staging-rebuild, staging-prebuilt]
      - name: prod-env
        activatedBy: [prod]

profiles:
  - name: dev-watch
  - name: dev-rebuild
  - name: staging-rebuild
  - name: staging-prebuilt
  - name: prod

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ory-kratos-db-generic

deploy:
  kubectl: {}
  statusCheck: true

portForward:
  - resourceType: Service
    namespace: auth
    resourceName: kratos--cluster-db-rw
    port: 5432

profiles:
  - name: dev-env

    manifests:
      kustomize:
        paths:
          - k8s/overlays/dev

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy-skaffold-hook@ory-kratos-db dev",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy-skaffold-hook@ory-kratos-db dev",
                  ]
                dir: .

  - name: staging-env

    manifests:
      kustomize:
        paths:
          - k8s/overlays/staging

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy-skaffold-hook@ory-kratos-db staging",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy-skaffold-hook@ory-kratos-db staging",
                  ]
                dir: .

  - name: prod-env

    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy-skaffold-hook@ory-kratos-db prod",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy-skaffold-hook@ory-kratos-db prod",
                  ]
                dir: .
