apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../base

namePrefix: dev- 

images:
- name: web-server
  newTag: latest

configMapGenerator:
- name: properties-map
  env: config.properties

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-server
      
    spec:
      template:
        spec:
          containers:
          - name: nginx
            imagePullPolicy: Never
