apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/domain

configMapGenerator:
  - name: auth-ory-stack-domain
    literals:
      - auth=auth.wosoom.com
