apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/secret
  - ../../components/namespace

images:
  - name: api-data-server
    ### automatically updated
    # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v0.0.8 # x-release-please-version

configMapGenerator:
  - name: properties-map-api-data-server
    env: .properties
