apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/tag-version
  - ../../components/secret
  - ../../components/namespace

configMapGenerator:
  - name: properties-map-api-data-server
    env: .properties
