version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Automatically merge pull requests once it passes all checks"
    validate: 
      - do: baseRef
        must_include:
          regex: 'master|main'
          message: 'Auto-merging is only enabled for default branch'    
      - do: headRef
        must_exclude:
          regex: '^release-please'
          message: 'Auto-merging is disabled for branches prefixed with "release-please"'
    pass:
      - do: merge
        merge_method: "squash"