### Github App: mergeable.readthedocs.io 

version: 2
mergeable:
  - when: status.*
    name: "Automatically merge pull requests labeled with 'automerge' once it passes all required Github checks"
    validate:
      - do: and
        validate:
          - do: baseRef  # Check the base branch
            must_include:
              regex: 'master|main'  # Only allow merging to default branch
              message: 'Auto-merging is only enabled for default branch'
          - do: headRef
            must_exclude:
              regex: '^release-please'
              message: 'Auto-merging is disabled for branches prefixed with "release-please"'
          - do: label
            must_include:
              regex: 'automerge'
              message: 'add label automerge'
          - do: label
            must_include:
              regex: 'ready-to-merge'
              message: 'add label ready-to-merge'

    pass:
      - do: checks
        status: 'success'
      - do: merge
        merge_method: "squash" 

    fail:
      - do: checks
        status: 'failure'
        payload: 
          title: "validator returned false"

    error:
      - do: checks
        status: 'error'
        payload: 
          title: "validator errored"

