# fixes service name association for resource (https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#builtin-namereference)

nameReference:
  - kind: Secret
    version: v1
    fieldSpecs:
      - kind: Cluster
        path: spec/bootstrap/initdb/secret/name
        version: v1
        group: postgresql.cnpg.io

