apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: ory-keto

requires: 
  - path: ../ory-keto-db
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

manifests:
  kustomize:
    paths:
    - k8s/base

deploy:
  kubectl: {}
  statusCheck: true

profiles:
- name: development
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@ory-keto development"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@ory-keto development"]
              dir: .

- name: production
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@ory-keto production"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@ory-keto production"]
              dir: .