apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components: 
- ../components/namespace

configMapGenerator:
  - name: properties-map-api-data-server
    env: .properties

secretGenerator:
  - name: secrets-api-data-server
    env: .env.development

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data
        
      spec:
        template:
          spec:
            containers:
            - name: api-data
              imagePullPolicy: Never

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data

      spec:
        replicas: 1
