apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namespace: api-data # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: api-data
    unsetOnly: true

images:
  - name: api-data
    newTag: latest

configMapGenerator:
  - name: properties-map-api-data-server
    env: .properties

secretGenerator:
  - name: secrets-api-data-server
    env: .env.development

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data
        
      spec:
        template:
          spec:
            containers:
            - name: api-data
              imagePullPolicy: Never

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data

      spec:
        replicas: 1
