[package]
name = "donation-app"
version = "0.4.16"
edition = "2021"


[workspace]
members = []
exclude = [
    "manifest/auth/ory-hydra",
    "manifest/auth/ory-keto",
    "manifest/auth/ory-kratos",
    "manifest/auth/ory-oathkeeper",
    "service/auth-token-exchange",
    "service/web-server/src-tauri",
]
