[package]
name = "donation-app"
version = "0.4.32"
edition = "2021"

[workspace]
members = ["library/protobuf-webhook", "library/protobuf-keto"]
exclude = [
    "service/auth-token-exchange",
    "service/webhook-handler",
    "service/web-server/src-tauri",
    "service/api-data-server",
]
