# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: monorepo

requires:
  - path: service/scaffold
    configs: [scaffold]          

  - path: service/web-server
    configs: []            

  - path: service/api-data
    configs: [api-data]  

