# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: monorepo

requires:
  - path: service/scaffold
    configs: [scaffold]

  # - path: service/web-server
  #   configs: [web-server]

  # - path: service/api-data
  #   configs: [api-data]  

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: monorepo-services-only

requires:
  - path: service/web-server
    configs: [web-server--no-dep]

  - path: service/api-data
    configs: [api-data--no-dep]

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: monorepo-scaffold-only

requires:
  - path: service/scaffold
    configs: [scaffold]          
