# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta12
kind: Config

requires:
  - path: scaffold
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: service/web-server
    configs: []            
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development]
     - name: production                               
       activatedBy: [production]
     - name: local-production
       activatedBy: [local-production]

  - path: service/api-data
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development]
     - name: production                               
       activatedBy: [production]
     - name: local-production
       activatedBy: [local-production]    

  - path: service/auth-token-exchange
    configs: []                 
    activeProfiles:                                     
    - name: development                               
      activatedBy: [development]
    - name: production                               
      activatedBy: [production]
    - name: local-production
      activatedBy: [local-production]    

profiles:
  - name: development
  - name: local-production
  - name: production
