# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: monorepo

requires:
  - path: service
    configs: [service]

  - path: platform
    configs: [platform]

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: monorepo-service-only

requires:
  - path: service
    configs: [service]

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: monorepo-platform-only

requires:
  - path: platform
    configs: [platform-core]
