# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta12
kind: Config

requires:
  - path: scaffold

  - path: service/web-server
  - path: service/api-data

profiles:
  - name: development
  - name: production
