apiVersion: apps/v1
kind: Deployment

metadata:
  name: webhook-handler
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: webhook-handler
          image: webhook-handler:latest
          ports:
            - containerPort: 3010
              name: webhook-handler

          env:
            - name: API_DATA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: properties-map-webhook-handler
                  key: API_DATA_ENDPOINT
                  optional: false
            - name: KAFKA_MESSAGE_QUEUE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: properties-map-webhook-handler
                  key: KAFKA_MESSAGE_QUEUE_ENDPOINT
                  optional: false

            # Kafka user credentials
            - name: KAFKA_SASL_USERNAME
              value: kafka-user
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-user
                  key: "password"
                  optional: false

          # envFrom:
            # - configMapRef:
            #     name: properties-map-webhook-handler 

            # - secretRef:
            #     name: kafka-user
