apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../base
- ../../web_server/production

namespace: donation-app

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: donation-app.com
