apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../base
- ../../web_server/production

namespace: donation-app

patches:
  - target:
      kind: HTTPRoute
      name: http-web
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: donation-app.com
