#!/bin/bash
set -e

add_vscode_workspaces#setup#task@monorepo() {(
    local manifest_file=".release-please-manifest.json"
    if [[ -f "$manifest_file" ]]; then
        mapfile -t workspacePath < <(jq -r 'keys[]' "$manifest_file" | grep -v '^.$')
    else
        echo "File '$manifest_file' not found."
    fi

    local workspace_file="workspace.code-workspace"
    # Ensure file exists with default structure
    cat <<EOF > "$workspace_file"
{
    "folders": [],
    "settings": {
        "workbench.colorCustomizations": {
            "activityBar.background": "#5A0A38",
            "titleBar.activeBackground": "#7E0E4E",
            "titleBar.activeForeground": "#FFFCFD"
        }
    }
}
EOF

    # Add each key as a new folder path
    local tmp=$(mktemp)
    cp "$workspace_file" "$tmp"
    
    for key in "${workspacePath[@]}"; do
        jq --arg path "$key" '.folders += [{"path": $path}]' "$tmp" > "$tmp.new"
        mv "$tmp.new" "$tmp"
    done
    
    echo '// autogenerated by adding workspaces paths from release-please configuration' | cat - "$tmp" > temp && mv temp "$workspace_file"
)}
