record_version#setup#task@monorepo() { 
    NODE_VERSION=$(node -v | cut -d 'v' -f2)
    PNPM_VERSION=$(pnpm --version | cut -d ' ' -f2)
    RUST_VERSION=$(rustc --version | awk '{print $2}') 
    CARGO_VERSION=$(cargo --version | awk '{print $2}')
    DOCKER_VERSION=$(docker version --format '{{.Server.Version}}')
    MINIKUBE_VERSION=$(/usr/bin/minikube version --short)  
    KUBERNETES_VERSION=$(kubectl version | awk '{printf "\t%s:\t%s\n", $1" "$2, $3}')
    KUSTOMIZE_VERSION=$(kustomize version)
    KOPS_VERSION=$(kops version --short)
    CILIUM_VERSION=$(cilium version --client)
    SKAFFOLD_VERSION=$(skaffold version)
    CONNTRACK_VERSION=$(conntrack -V | awk '{print $2}')
    POSTGRESQL_VERSION=$(psql --version | awk '{print $3}')



    t=$(mktemp)
    echo '--- autogenerated section ---' > "$t"
    echo "Node.js version: ${NODE_VERSION}" >> "$t"
    echo "pnpm version: ${PNPM_VERSION}" >> "$t"
    echo "Rust version: ${RUST_VERSION}" >> "$t"
    echo "Cargo version: ${CARGO_VERSION}" >> "$t"
    echo "Docker version: ${DOCKER_VERSION}" >> "$t"
    echo "Minikube version: ${MINIKUBE_VERSION}" >> "$t"
    printf "Kubernetes version: \n%s\n" "$KUBERNETES_VERSION" >> "$t"
    echo "Kustomize version: ${KUSTOMIZE_VERSION}" >> "$t"
    echo "kOps version: ${KOPS_VERSION}" >> "$t"
    echo "---\nCilium version: ${CILIUM_VERSION}\n" >> "$t"
    echo "Skaffold version: ${SKAFFOLD_VERSION}" >> "$t"
    echo "Conntrack version: ${CONNTRACK_VERSION}" >> "$t"
    echo "PostgreSQL version: ${POSTGRESQL_VERSION}" >> "$t"
    yq --version >> "$t"
    mc --version >> "$t"

    # write to README.md in section ```autogenerated-versions```
    sed -i '/^```autogenerated-versions$/,/^```$/c\```autogenerated-versions\n'"$(cat "$t" | sed ':a;N;$!ba;s/\n/\\n/g')"'\n```' README.md

    cat "$t"
}