apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: api-data-database

requires:
  - path: .
    configs: [api-data-database-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: api-data-database-generic

build:
  local: 
    push: false
    useBuildkit: true
  tagPolicy:
    # sha256: {} 
    gitCommit: {}

deploy:
  kubectl: {}
  statusCheck: true

portForward:
  - resourceType: Service
    namespace: api-data
    resourceName: api-data--cluster-db-rw
    port: 5432

profiles:

- name: development

  build:
    tagPolicy:
      envTemplate:
        template: "17.0.0-dev" # tag used in CNPG for local development (NOTE: CNPG doesn't accept 'latest' tag)
    artifacts:
    - image: api-data-database
      context: .
      docker:
        target: final
        dockerfile: Dockerfile
        buildArgs: {}

  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@api-data-database development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@api-data-database development"]
              dir: .

- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@api-data-database production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@api-data-database production"]
              dir: .
