apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: api-data-database

deploy:
  kubectl: {}
  statusCheck: true

profiles:

- name: development
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@api-data-database development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@api-data-database development"]
              dir: .

- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@api-data-database production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@api-data-database production"]
              dir: .
