apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: prod-

images:
  - name: web-server
    newName: ghcr.io/szn-app/donation-app/web-server
    newTag: v0.0.64

configMapGenerator:
  - name: properties-map-web-server
    env: config.properties

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-server
        
      spec:
        template:
          spec:
            containers:
            - name: nginx
              imagePullPolicy: Always
