apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../base

namePrefix: prod- 
namespace: donation-app

images:
- name: web-server
  newName: ghcr.io/szn-app/donation-app/web-server
  newTag: latest

configMapGenerator:
  - name: properties-map
    env: config.properties

patches: 
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-server

      spec:
        replicas: 2

      