apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: api-data-domain
    literals:
      - api=api.wosoom.com

replacements:
  - source:
      kind: ConfigMap
      name: api-data-domain
      fieldPath: data.api
      
    targets:
      - select:
          kind: HTTPRoute
          name: https-api-data
        fieldPaths:
          - spec.hostnames.[=api.donation-app.local]
        options:
          create: false
          
      - select:
          kind: HTTPRoute
          name: internal-api-data
        fieldPaths:
          - spec.hostnames.[=api.donation-app.local]
        options:
          create: false

      - select:
          kind: HTTPRoute
          name: http-api-data-redirect
        fieldPaths:
          - spec.hostnames.[=api.donation-app.local]
        options:
          create: false

