apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: api-data-object-store-domain
      fieldPath: data.minio
      
    targets:
      - select:
          kind: HTTPRoute
          name: https-k8s-minio
        fieldPaths:
          - spec.hostnames.[=minio.k8s.donation-app.local]
        options:
          create: false
          
      - select:
          kind: HTTPRoute
          name: internal-k8s-minio
        fieldPaths:
          - spec.hostnames.[=minio.k8s.donation-app.local]
        options:
          create: false

      - select:
          kind: HTTPRoute
          name: http-k8s-minio-redirect
        fieldPaths:
          - spec.hostnames.[=minio.k8s.donation-app.local]
        options:
          create: false


