apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: api-data-k8s

manifests:
  kustomize:
    paths:
    - ./k8s/base

deploy:
  kubectl: {}
  statusCheck: true

---

# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: api-data

requires:
  - path: .
    configs: [api-data-k8s]

  - path: database
    configs: [api-data-database]

  - path: object-store
    configs: [api-data-object-store]                 

  - path: server
    configs: []            
