apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: api-data

requires:
  - path: .
    configs: [api-data-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development]
      - name: local-production
        activatedBy: [local-production]
      - name: production
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: api-data--no-dep

requires:
  - path: .
    configs: [api-data-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development]
      - name: local-production
        activatedBy: [local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: api-data-k8s

manifests:
  kustomize:
    paths:
    - ./k8s/base

deploy:
  kubectl: {}
  statusCheck: true

---

# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: api-data-generic

requires:
  - path: .
    configs: [api-data-k8s]

  - path: database
    configs: [api-data-database]

  - path: object-store
    configs: [api-data-object-store]                 

  - path: server
    configs: []            
