# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta12
kind: Config

requires:
  - path: database
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: object-store
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: server
    configs: []            
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development]
     - name: production         
       activatedBy: [production]
     - name: local-production
       activatedBy: [local-production]

profiles:
  - name: development
  - name: local-production
  - name: production
