apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../dev

# TODO:
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data

      spec:
        template:
          spec:
            containers:
              - name: api-data
                volumeMounts:
                  - name: volume-target
                    mountPath: /app/
            volumes:
              - name: volume-target
                hostPath: 
                  type: Directory
                  path: /mnt/repo-root/service/api-data/server
