apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: ory-admin-domain
    literals:
      - ory_admin=ory-admin.k8s.wosoom.com

replacements:
  - source:
      kind: ConfigMap
      name: ory-admin-domain
      fieldPath: data.ory_admin
    targets:
      - select:
          kind: HTTPRoute
          name: https-k8s-ory-admin
        fieldPaths:
          - spec.hostnames.[=ory-admin.k8s.donation-app.local]
        options:
          create: false
      - select:
          kind: HTTPRoute
          name: internal-k8s-ory-admin
        fieldPaths:
          - spec.hostnames.[=ory-admin.k8s.donation-app.local]
        options:
          create: false
      - select:
          kind: HTTPRoute
          name: http-k8s-ory-admin-redirect
        fieldPaths:
          - spec.hostnames.[=ory-admin.k8s.donation-app.local]
        options:
          create: false
