apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/secret
  - ../../components/namespace
  - ../../components/domain

images:
  - name: api-data-server
    ### automatically updated
    # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v0.1.6 # x-release-please-version

configMapGenerator:
  - name: properties-map-api-data-server
    env: .properties

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data-server
        
      spec:
        template:
          spec:
            containers:
            - name: api-data-server
              imagePullPolicy: Always
