apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-ui
spec:
  replicas: 2
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: auth-ui
          image: auth-ui:latest
          ports:
            - containerPort: 4455
              name: http-auth-ui
          env:
            - name: PORT
              value: "4455"
            - name: KRATOS_PUBLIC_URL
              value: http://ory-kratos:4433/
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets-auth-ui
                  key: COOKIE_SECRET
            - name: CSRF_COOKIE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets-auth-ui
                  key: CSRF_COOKIE_NAME
            - name: CSRF_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets-auth-ui
                  key: CSRF_COOKIE_SECRET
          envFrom:
            - configMapRef:
                name: properties-map-auth-ui
            # - secretRef:
            #     name: secrets-auth-ui
