apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# namespace: auth # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: auth
    unsetOnly: true

images:
  - name: auth-ui
    newName: ghcr.io/szn-app/donation-app/auth-ui
    ### automatically updated
    # x-release-please-start-version
    newTag: v1.2.0
    # x-release-please-end


configMapGenerator:
  - name: properties-map-auth-ui
    namespace: auth
    env: .env

secretGenerator:
  - name: secrets-auth-ui
    namespace: auth
    envs:
      - secret.env

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-ui
        
      spec:
        template:
          spec:
            containers:
            - name: auth-ui
              imagePullPolicy: Always
