apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: gateway # cilium adds a prefix "cilium-gateway-*"
  namespace: gateway
  annotations:
    # automatically create and renew Let's Encrypt certificates
    cert-manager.io/cluster-issuer: staging-cluster-issuer # when testing to avoid Let's Encrypt rate limit of `production-cluster-issuer`

spec:
  gatewayClassName: cilium
  # NOTE: order is important as kustomize targets indecies of listners
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "wosoom.com"
      allowedRoutes:
        namespaces:
          from: All

    - name: http-subdomain
      protocol: HTTP
      port: 80
      hostname: "*.wosoom.com"
      allowedRoutes:
        namespaces:
          from: All

    - name: direct-ip
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: https
      protocol: HTTPS
      port: 443
      hostname: "donation-app.test"
      allowedRoutes:
        namespaces:
          from: All # required for letsecrypt
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-certificate-donation-app
            group: ""

    - name: https-api
      protocol: HTTPS
      port: 443
      hostname: "api.donation-app.test"
      allowedRoutes:
        namespaces:
          from: All # required for letsecrypt
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-certificate-donation-app
            group: ""

    - name: https-auth
      protocol: HTTPS
      port: 443
      hostname: "auth.donation-app.test"
      allowedRoutes:
        namespaces:
          from: All # required for letsecrypt
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-certificate-donation-app
            group: ""

    - name: https-k8s-longhorn
      protocol: HTTPS
      port: 443
      hostname: "longhorn.k8s.donation-app.test"
      allowedRoutes:
        namespaces:
          from: All # required for letsecrypt
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-certificate-admin-donation-app
            group: ""

    - name: https-k8s-dashboard
      protocol: HTTPS
      port: 443
      hostname: "dashboard.k8s.donation-app.test"
      allowedRoutes:
        namespaces:
          from: All # required for letsecrypt
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-certificate-admin-donation-app
            group: ""

    - name: https-k8s-hubble
      protocol: HTTPS
      port: 443
      hostname: "hubble.k8s.donation-app.test"
      allowedRoutes:
        namespaces:
          from: All # required for letsecrypt
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-certificate-admin-donation-app
            group: ""

    - name: https-k8s-ory-admin
      protocol: HTTPS
      port: 443
      hostname: "ory-admin.k8s.donation-app.test"
      allowedRoutes:
        namespaces:
          from: All # required for letsecrypt
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-certificate-admin-donation-app
            group: ""
