# redirect HTTP to HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: http-redirect
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
      sectionName: http

  hostnames:
    - "donation-app.test"

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: http-subdomain-redirect
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
      sectionName: http-subdomain

  hostnames:
    - "*.donation-app.test"

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: ip-redirect
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
      sectionName: direct-ip

  rules:
    # - filters:
    #     - type: RequestRedirect
    #       requestRedirect:
    #         hostname: "localhost"
    #         scheme: http
    #         statusCode: 301
    - backendRefs:
        # kubernetees service
        - name: web-server
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
