# redirect HTTP to HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: http-redirect
spec:
  parentRefs:
    - name: gateway
      namespace: nginx-gateway
      sectionName: http # name of listener

  hostnames:
    - donation-app.test

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: http-redirect-subdomain
spec:
  parentRefs:
    - name: gateway
      namespace: nginx-gateway
      sectionName: http-subdomain-all # name of listener

  hostnames:
    - "*.donation-app.test"

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: http-redirect-ip-access
spec:
  parentRefs:
    - name: gateway
      namespace: nginx-gateway
      sectionName: http-redirect-ip-access # name of listener

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: http
            hostname: "localhost"
            statusCode: 301
