apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- namespace.yml
- gateway.yml
- cert-manager-cluster-issuer.yml
- http-route.yml
- https-route.yml

configurations: 
- name-reference.kustomize-config.yml