apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yml
  - cert-manager-cluster-issuer.yml
  - direct-ip-route.yml

configurations:
  - name-reference.kustomize-config.yml
