import type { CodegenConfig } from "@graphql-codegen/cli";
import { loadConfig } from "graphql-config";
import { z } from "zod";

const c = loadConfig({});

const config: CodegenConfig = {
  schema: (await c)?.getDefault().schema,
  documents: (await c)?.getDefault().documents,
  overwrite: true,
  ignoreNoDocuments: true,
  // root-level config will apply to all generates enteries
  config: {
    // handles static type mappings (without parsing) mapping graphql objects to typescript types
    scalars: {
      UUID: "string",
      ID: "string",
      DateTime: {
        input: "string", // GraphQL input expects a string (e.g., "2023-01-01T00:00:00Z")
        output: "Date", // TypeScript output is a Date object
      },
      JSON: "{ [key: string]: any }",
      Decimal: "number", // If you have decimals in your schema
      BigInt: "number", // BigInt can be handled as number (or string depending on your use case)
      URL: "string", // URL types can be converted to strings
    },
  },
  generates: {
    // if schema is provided as endpoint then schema-ast plugin will generate the graphql schema
    "./config/schema-autogen.graphql": {
      plugins: ["schema-ast"],
      // https://the-guild.dev/graphql/codegen/plugins/other/schema-ast
      config: {
        includeDirectives: true,
      },
    },

    /**
     * - https://the-guild.dev/graphql/codegen/docs/guides/react-vue
     *
     * uses graphql-request as fetcher by default
     */
    "src/modules/graphql/autogenerated/": {
      preset: "client",
      // https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#documentmode
      config: {
        documentMode: "string", // generated function returns a wrapper over string
        // documentMode: "document", // generated function returns an AST // not required with graphql-request setup (causes issues for somereason 'gql is not defined' in generated code)

        // https://the-guild.dev/graphql/codegen/plugins/presets/preset-client
        useTypeImports: true,
      },
    },

    // NOTE: there is currently an issue with client-present, thus need to split the config separately
    //
    // https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-validation-schema
    // https://github.com/colinhacks/zod
    //
    // issue: not generating schemas for queries only inputs and data object models https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/472
    "src/modules/graphql/autogenerated/runtime-validate.ts": {
      plugins: [
        // "typescript", // not needed because already taken care of by preset-client
        "typescript-validation-schema",
      ],
      config: {
        schema: "zod",
        importFrom: "./graphql.ts",
        withObjectType: true,
        // see: https://www.graphql-code-generator.com/plugins/typescript
        strictScalars: true,
        // parse and validate
        // NOTE to achieve non-strict validation/parsing: by making all types optional with .optional() zod in mapping, it permits to use partial queries (that do not cover all Graphql requited fields); Another apporach to make validation lenient is to use .partial() or .deepPartial() methods on runtime
        scalarSchemas: {
          // Overrides built-in ID scalar to both input and output types as string.
          // see: https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#scalars
          ID: "z.string()",
          DateTime: "z.coerce.date()", // Coerce ISO strings to Date objects
          UUID: "z.string()",
          JSON: "z.record(z.any())",
          Decimal: "z.number()",
          BigInt: "z.number()", // or can be set to  z.string()
          URL: "z.string().url()",
          String: "z.string()",
          Int: "z.number()",
        },
      },
    },

    /*
    // older approach - using preset client is now recommended instead;
    // generates in typescript: graphql data object types, graphql operations types, graphql document queries, tanstack query + graphql-request react hooks for the queries
    "src/modules/graphql/autogenerated/sdk.ts": {
      // generates SDK for graphql-request in addition to types
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-react-query",
      ],
      config: {
        documentMode: "string",
        fetcher: "graphql-request",
        reactQueryVersion: 5,
      },
    }, 
    */
  },
  hooks: {
    // afterAllFileWrite: ["prettier --write"]
  },
};

export default config;
