apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: web-server

build:
  local: 
    push: false
    useBuildkit: true
  tagPolicy:
    sha256: {} 

deploy:
  kubectl: {}
  statusCheck: true
  
portForward:
  - resourceType: Service
    resourceName: web-server
    namespace: donation-app
    port: 80

profiles:

- name: development
  # activation:
  #   - kubeContext: minikube
      
  build: 
    artifacts:
    - image: web-server
      context: .
      docker:
        target: development
        dockerfile: Dockerfile
        buildArgs: {}
      # NOTE: limitations https://skaffold.dev/docs/filesync/#limitations
      sync:
        manual:
        - src: "src/**"
          dest: .
        - src: "src-tauri/**"
          dest: .
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  deploy:
    kubeContext: minikube

# build production mode and run with local dev settings
- name: local-production

  build: 
    local: 
      push: false 
      tryImportMissing: false
    artifacts:
    - image: web-server
      context: .
      docker:
        target: production
        dockerfile: Dockerfile
        buildArgs: 
          CONFIG: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
