apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: web-server

requires:
  - path: ../../scaffold

build:
  local: 
    push: false
  tagPolicy:
    sha256: {} 

deploy:
  kubectl: {}
  statusCheck: true
  
portForward:
  - resourceType: deployment
    resourceName: web-server
    port: 80
    localPort: 8080

profiles:

- name: development
  activation:
    - kubeContext: minikube
      
  build: 
    artifacts:
    - image: web-server
      context: .
      docker:
        target: development
        dockerfile: Dockerfile
        buildArgs: {}
      # NOTE: limitations https://skaffold.dev/docs/filesync/#limitations
      sync:
        manual:
        - src: "src/**"
          dest: .
        - src: "src-tauri/**"
          dest: .
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  deploy:
    kubeContext: minikube

- name: production

  build: 
    artifacts:
    - image: web-server
      context: .
      docker:
        target: production
        dockerfile: Dockerfile
        buildArgs: {}
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
