apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
- ../components/namespace

configMapGenerator:
  - name: properties-map-webhook-handler
    env: .properties
