[package]
name = "shared_protobuf_webhook"
version = "0.4.34"
edition = "2021"

[dependencies]
tonic = "0.13.0"
prost = "0.13.5"
tonic-reflection = "0.13.0"
prost-types = "0.13.5"

[build-dependencies]
tonic-build = "0.13.0"
