apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namespace: default # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: default
    unsetOnly: true

patches:
  - target:
      kind: HTTPRoute
      name: https-k8s-kafka
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "kafka.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-k8s-kafka
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "kafka.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-k8s-kafka-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "kafka.k8s.wosoom.com"
