import { faker } from "@faker-js/faker";
import {
  Account,
  Profile,
  Community,
  Committee,
  Category,
  Location,
  Item,
  Media,
  Collection,
  Publish,
  ProfileType,
  CommunityType,
  CommitteeRole,
  ItemCondition,
  ItemStatus,
  ItemType,
  ItemIntentAction,
  MediaType,
  CollectionType,
  CollectionVisibility,
} from "@/modules/graphql/autogenerated/graphql";

export class MockDataGenerator {
  static generateAccount(): Account {
    return {
      id: faker.string.uuid(),
      createdAt: faker.date.past(),
      remarks: faker.lorem.sentence(),
    };
  }

  static generateProfile(accountId: string): Profile {
    return {
      id: faker.number.int(),
      name: faker.person.fullName(),
      description: faker.lorem.paragraph(),
      variant: faker.helpers.arrayElement([
        ProfileType.Individual,
        ProfileType.Company,
        ProfileType.Organization,
      ]),
      owner: accountId,
      createdBy: accountId,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    };
  }

  static generateCommunity(accountId: string): Community {
    return {
      id: faker.number.int(),
      title: faker.company.name(),
      description: faker.lorem.paragraph(),
      variant: faker.helpers.arrayElement([
        CommunityType.Organized,
        CommunityType.Solo,
      ]),
      owner: accountId,
      createdBy: accountId,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    };
  }

  static generateCommittee(communityId: number, profileId: number): Committee {
    return {
      idCommunity: communityId,
      idProfile: profileId,
      memberRole: faker.helpers.arrayElement([
        CommitteeRole.Member,
        CommitteeRole.Organizer,
      ]),
      joined_at: faker.date.past(),
    };
  }

  static generateCategory(parentId?: number): Category {
    return {
      id: faker.number.int(),
      title: faker.commerce.department(),
      description: faker.lorem.sentence(),
      categoryParent: parentId,
    };
  }

  static generateLocation(_profileId: string): Location {
    return {
      id: faker.number.int(),
      addressLine1: faker.location.streetAddress(),
      addressLine2: faker.location.secondaryAddress(),
      city: faker.location.city(),
      state: faker.location.state(),
      country: faker.location.country(),
      district: faker.location.county(),
      entranceNote: faker.lorem.sentence(),
      createdAt: faker.date.past(),
    };
  }

  static generateItem(
    categoryId: number,
    locationId: number,
    createdBy: string,
  ): Item {
    return {
      id: faker.number.int(),
      title: faker.commerce.productName(),
      description: faker.lorem.paragraph(),
      variant: faker.helpers.arrayElement([
        ItemType.Inkind,
        ItemType.Monetary,
        ItemType.Service,
        ItemType.Inquiry,
      ]),
      condition: faker.helpers.arrayElement([
        ItemCondition.BrandNew,
        ItemCondition.PreOwnedBarelyUsed,
        ItemCondition.PreOwnedUsable,
        ItemCondition.PreOwnedDamaged,
      ]),
      status: faker.helpers.arrayElement([
        ItemStatus.Active,
        ItemStatus.Archived,
        ItemStatus.Disabled,
        ItemStatus.Draft,
      ]),
      intentAction: faker.helpers.arrayElement([
        ItemIntentAction.Offer,
        ItemIntentAction.Request,
      ]),
      category: categoryId,
      location: locationId,
      createdBy: createdBy,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
      viewsCount: faker.number.int({ min: 0, max: 1000 }),
      isReported: faker.datatype.boolean(),
    };
  }

  static generateMedia(itemId: number): Media {
    return {
      id: faker.number.int(),
      idItem: itemId,
      variant: faker.helpers.arrayElement([
        MediaType.Image,
        MediaType.Video,
        MediaType.Document,
      ]),
      url: faker.image.url(),
      caption: faker.lorem.sentence(),
      createdAt: faker.date.past(),
    };
  }

  static generateCollection(communityId: number): Collection {
    return {
      id: faker.number.int(),
      idCommunity: communityId,
      title: faker.commerce.productName(),
      variant: faker.helpers.arrayElement([
        CollectionType.Featured,
        CollectionType.Regular,
      ]),
      visibility: faker.helpers.arrayElement([
        CollectionVisibility.Public,
        CollectionVisibility.Restricted,
      ]),
      position: faker.number.int({ min: 1, max: 100 }),
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    };
  }

  static generatePublish(
    collectionId: number,
    itemId: number,
    addedBy: string,
  ): Publish {
    return {
      idCollection: collectionId,
      idItem: itemId,
      position: faker.number.int({ min: 1, max: 100 }),
      note: faker.lorem.sentence(),
      addedBy: addedBy,
      posted_on: faker.date.past(),
    };
  }
}
