apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/domain
  - ../../components/external-authorizer

configMapGenerator:
  - name: envoy-cors-domain
    literals:
      - root=https://wosoom.com
      - api=https://api.wosoom.com
