apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/dashboard
  - ../../components/hubble
  - ../../components/longhorn
  - ../../components/ory-stack

# namePrefix: prod-
# nameSuffix: -v1

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: "worker"
