apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/tag-version
  - ../../components/namespace

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-token-exchange
        
      spec:
        template:
          spec:
            containers:
            - name: auth-token-exchange
              imagePullPolicy: Always
