apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: kafka-message-queue

requires:
  - path: .
    configs: [kafka-message-queue-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: kafka-message-queue-generic

deploy:
  kubectl: {}
  statusCheck: true

portForward:
  - resourceType: Service
    namespace: kafka-message-queue
    resourceName: kafka-message-queue-cluster-kafka-bootstrap
    port: tcp-http

profiles:

- name: development
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@kafka-message-queue development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@kafka-message-queue development"]
              dir: .

- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@kafka-message-queue production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@kafka-message-queue production"]
              dir: .
