apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: envoy-proxy

requires:
  - path: .
    configs: [envoy-proxy-generic]

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: envoy-proxy-generic

manifests:
  kustomize:
    paths:
    - k8s/base

deploy:
  kubectl: {}
