apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: envoy-proxy

requires:
  - path: .
    configs: [envoy-proxy-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: envoy-proxy-generic

manifests:
  kustomize:
    paths:
    - k8s/base

deploy:
  kubectl: {}

profiles:
- name: development
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
