apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: gateway
spec:
  selfSigned: {}

---
# create a common tls certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shared-tls-certificate
  namespace: gateway
spec:
  secretName: shared-tls-certificate
  dnsNames:
    - "*.donation-app.local"
    - donation-app.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
