# development setup with ingress to resolve dns: donation-app.test → ingress-dns → minikube ip  → ingress  → gateway

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../base
- ../../web_server/development
- ingress.yml

patches:
  - target:
      kind: HTTPRoute
      name: http-web
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: donation-app.test
  
  # set namespace if doesn't exist on resource
  - target:
      namespace: default
    patch: |-
      - op: add
        path: /metadata/namespace
        value: donation-app
