# development setup with ingress to resolve dns: donation-app.test → ingress-dns → minikube ip  → ingress  → gateway

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yml

# namespace: donation-app # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: donation-app
    unsetOnly: true

patches:
  # set namespace if doesn't exist on resource
  # - target:
  #     namespace: default
  #   patch: |-
  #     - op: add
  #       path: /metadata/namespace
  #       value: donation-app

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: "nginx"
