# development setup with ingress to resolve dns: donation-app.local → ingress-dns → minikube ip  → ingress  → gateway

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # - ingress.yaml

components:
  - ../components/namespace
  - ../components/tls-certificate/dev

patches:
  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: "nginx"
