# yaml config options passed to Kratos
# https://www.ory.sh/docs/kratos/reference/configuration

kratos:
  # TODO:
  development: true
  config:
    dev: true

    log:
      level: debug
      leak_sensitive_values: false
      redaction_text: ""
      format: json

    # dsn: memory # NOTE: use for development only
    # NOTE: username and password are replaced using regex
    dsn: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres-kratos-postgresql:5432/kratos_db?sslmode=disable&max_conns=20&max_idle_conns=4"

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity-schema.json

        # NOTE: if the above doesn't work, encode the schema.json content as base64 and copy over here
        # - id: default
        #   url: base64://ew0KICAiJGlkIjogImh0dHBzO....=

    serve:
      # links to generete for kratos-public internal server
      public:
        base_url: https://auth.wosoom.com/authenticate
        port: 4433
        cors:
          enabled: true
          allowed_origins:
            # - "*" # NOTE: use for debug only
            - https://wosoom.com/
            - https://auth.wosoom.com/
            - https://*.wosoom.com/
          allowed_methods:
            - GET
            - OPTIONS
            - PUT
            - PATCH
            - DELETE
      admin:
        base_url: http://kratos-admin/
        port: 4434

    selfservice:
      # links to generate for kratos ui pages
      default_browser_return_url: https://wosoom.com/
      allowed_return_urls:
        - https://wosoom.com/
        - https://auth.wosoom.com/
        - https://*.wosoom.com/

      methods:
        password: # email/password authentication
          enabled: true # default enabled
        totp: # MFA
          config:
            issuer: donation-app
          enabled: true
        lookup_secret: # backup codes for 2FA
          enabled: true
        link: # one-time link authentication
          enabled: true
        code: # one-time code authentication
          enabled: true
        oidc:
          enabled: false
          # example:
          # config:
          #   providers:
          # - id: github # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
          #   provider: github
          #   client_id: _ # Replace this with the Client ID
          #   client_secret: _ # Replace this with the Client secret
          #   issuer_url: https://api.github.com # Replace this with the providers issuer URL
          #   mapper_url: "base64://bG9jYWwgY2xhaW1zID0gc3RkLmV4dFZhcignY2xhaW1zJyk7Cgp7CiAgaWRlbnRpdHk6IHsKICAgIHRyYWl0czogewogICAgICBlbWFpbDogY2xhaW1zLmVtYWlsLAogICAgICB1c2VybmFtZTogY2xhaW1zLm5hbWUsCiAgICAgIHBob25lX251bWJlcjoxMjMKICAgIH0sCiAgfSwKfQ=="
          #   scope:
          #     - read:user
          #     - user:email
          #   requested_claims:
          #     id_token:
          #       email:
          #         essential: true
          #       username:
          #         essential: true
          #       phone_number:
          #         essential: false

      flows:
        # default return url if no uri parameter set or no service-level default_browser_return_url config set
        login:
          ui_url: https://auth.wosoom.com/login
          lifespan: 10m
        logout:
          after:
            default_browser_return_url: https://wosoom.com/
        registration:
          ui_url: https://auth.wosoom.com/registration
          lifespan: 10m
          after:
            default_browser_return_url: https://wosoom.com/
            password:
              hooks:
                - hook: session
                # - hook: show_verification_ui
        verification:
          enabled: true
          ui_url: https://auth.wosoom.com/verification
          # use: code
          after:
            default_browser_return_url: https://wosoom.com/
        settings:
          ui_url: https://auth.wosoom.com/settings
          privileged_session_max_age: 15m
          # required_aal: highest_available
        recovery:
          enabled: true
          ui_url: https://auth.wosoom.com/recovery
          # use: code
        error:
          ui_url: https://auth.wosoom.com/error

    secrets:
      default:
        - should-be-autogenerated-and-replaced # replaced with helm command argument
      cookie:
        - should-be-autogenerated-and-replaced # replaced with helm command argument
      cipher:
        - should-be-autogenerated-and-replaced # replaced with helm command argument

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    cookies:
      domain: ".wosoom.com" # allow cookie for root and subdomains
      path: "/"
      same_site: Strict

    feature_flags:
      use_continue_with_transitions: true # allow flexible flows (e.g. agree on terms in the registration flow, etc.)

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true # TODO: update with deployed one

    oauth2_provider:
      url: http://hydra-admin/

    # convert session to JWT for easier handling and integration
    # possible to customize the identity token information and custom logic JWT returned based on roles
    # https://www.ory.sh/docs/identities/session-to-jwt-cors#end-to-end-example
    session:
      whoami:
        tokenizer:
          templates:
            jwt_example_template: # template name
              jwks_url: http://hydra-admin/admin/keys/hydra.jwt.access-token
              # [manual update] base64 of a Go function with the JWT fields definition
              claims_mapper_url: base64://CmxvY2FsIGNsYWltcyA9IHN0ZC5leHRWYXIoJ2NsYWltcycpOwpsb2NhbCBzZXNzaW9uID0gc3RkLmV4dFZhcignc2Vzc2lvbicpOwoKewogIGNsYWltczogewogICAgaXNzOiBjbGFpbXMuaXNzICsgIi9hZGRpdGlvbmFsLWNvbXBvbmVudCIsCiAgICBzY2hlbWFfaWQ6IHNlc3Npb24uaWRlbnRpdHkuc2NoZW1hX2lkLAogICAgc2Vzc2lvbjogc2Vzc2lvbiwKICB9Cn0=
              ttl: 10m
