apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: web-server
    newTag: latest

# configMapGenerator:
#   - name: properties-map-web-server
#     env: config.properties

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-server
        
      spec:
        template:
          spec:
            containers:
            - name: nginx
              imagePullPolicy: Never

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-server

      spec:
        replicas: 1

