apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: app-scaffold-domain-config
      fieldPath: data.test
    targets:
      - select:
          kind: HTTPRoute
          name: https-test
        fieldPaths:
          - spec.hostnames.[=test.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: internal-test
        fieldPaths:
          - spec.hostnames.[=test.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: http-test-redirect
        fieldPaths:
          - spec.hostnames.[=test.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring

  - source:
      kind: ConfigMap
      name: app-scaffold-domain-config
      fieldPath: data.dashboard
    targets:
      - select:
          kind: HTTPRoute
          name: https-k8s-dashboard
        fieldPaths:
          - spec.hostnames.[=dashboard.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: internal-k8s-dashboard
        fieldPaths:
          - spec.hostnames.[=dashboard.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: http-k8s-dashboard-redirect
        fieldPaths:
          - spec.hostnames.[=dashboard.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring

  - source:
      kind: ConfigMap
      name: app-scaffold-domain-config
      fieldPath: data.hubble
    targets:
      - select:
          kind: HTTPRoute
          name: https-k8s-hubble
        fieldPaths:
          - spec.hostnames.[=hubble.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: internal-k8s-hubble
        fieldPaths:
          - spec.hostnames.[=hubble.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: http-k8s-hubble-redirect
        fieldPaths:
          - spec.hostnames.[=hubble.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring

  - source:
      kind: ConfigMap
      name: app-scaffold-domain-config
      fieldPath: data.longhorn
    targets:
      - select:
          kind: HTTPRoute
          name: https-k8s-longhorn
        fieldPaths:
          - spec.hostnames.[=longhorn.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: internal-k8s-longhorn
        fieldPaths:
          - spec.hostnames.[=longhorn.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: http-k8s-longhorn-redirect
        fieldPaths:
          - spec.hostnames.[=longhorn.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring




