apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../../gateway/development
  - ../../web_server/development
  - ../../auth_ui/development
  - ../../auth-ory-admin-ui
