apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../../gateway/development
  - ../../envoy_proxy/base
  - ../../auth-token-exchange/development
  - ../../web_server/development
  - ../../auth_ui/development
  - ../../auth-ory-admin-ui/development
  - ../../auth/development
  - ../route

# namePrefix: prod-
# nameSuffix: -v1

configurations:
  - ./name-reference.kustomize-config.yml
