apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: scaffold-k8s

build:
  local: {}
  artifacts: []

deploy:
  kubectl: {}
  statusCheck: true

profiles:
  - name: development
    manifests:
      kustomize:
        paths:
        - ./k8s/overlays/dev

  - name: production
    manifests:
      kustomize:
        paths:
        - ./k8s/overlays/prod

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: scaffold

requires:
  - path: .
    configs: [scaffold-k8s]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

  - path: ../cilium-gateway
    configs: [cilium-gateway]                 

  - path: ../envoy-proxy
    configs: [envoy-proxy]                 

  - path: ../auth-ory-stack
    configs: [auth-ory-stack]

  - path: ../auth-ory-admin-ui
    configs: [auth-ory-admin-ui]                 

  - path: ../auth-ui
    configs: [auth-ui]                 

  - path: ../auth-token-exchange
    configs: [auth-token-exchange]                 

  - path: ../pgadmin4
    configs: [pgadmin4]                 

  - path: ../kafka-message-queue
    configs: [kafka-message-queue]                 

  - path: ../webhook-handler
    configs: [webhook-handler]                 

  - path: ../kafka-ui
    configs: [kafka-ui]                 

profiles:
  - name: development
  - name: local-production
  - name: production
