# project root kustomization file that includes all other kustomizations
apiVersion: skaffold/v4beta12
kind: Config

requires:
  - path: ./k8s
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ../cilium-gateway
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ../envoy-proxy
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ../auth-ory-stack
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ../auth-ory-admin-ui
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

  - path: ../auth-ui
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development]
     - name: production                               
       activatedBy: [production]
     - name: local-production
       activatedBy: [local-production]

  - path: ../auth-token-exchange
    configs: []                 
    activeProfiles:                                     
    - name: development                               
      activatedBy: [development]
    - name: production                               
      activatedBy: [production]
    - name: local-production
      activatedBy: [local-production]    

profiles:
  - name: development
  - name: production