# NOTE: namespaces must exsit before skaffold can create resources in them

apiVersion: v1
kind: Namespace

metadata:
  name: donation-app

---
apiVersion: v1
kind: Namespace

metadata:
  name: auth
---
apiVersion: v1
kind: Namespace

metadata:
  name: gateway
---
apiVersion: v1
kind: Namespace

metadata:
  name: kafka-message-queue
---
