# project root kustomization file that includes all other kustomizations
apiVersion: skaffold/v4beta12
kind: Config

build:
  local: {}
  artifacts: []
deploy:
  kubectl: {}
  statusCheck: true

requires:
#   - path: ../service/cilium-gateway # handled as reference in kustomize
    # configs: []                 
    # activeProfiles:                                     
    #  - name: development                               
    #    activatedBy: [development]
    #  - name: production                               
    #    activatedBy: [production]


  # - path: ../service/envoy-proxy # handled as reference in kustomize
  #   configs: []                 
  #   activeProfiles:                                     
  #    - name: development                               
  #      activatedBy: [development]
  #    - name: production                               
  #      activatedBy: [production]

  - path: ../service/auth-ory-stack
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development]
     - name: production                               
       activatedBy: [production]

#   - path: ../service/auth-ory-admin-ui # handled as reference in kustomize
    # configs: []                 
    # activeProfiles:                                     
    #  - name: development                               
    #    activatedBy: [development]
    #  - name: production                               
    #    activatedBy: [production]

  - path: ../service/auth-ui
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development]
     - name: production                               
       activatedBy: [production]
     - name: local-production
       activatedBy: [local-production]

  - path: ../service/auth-token-exchange
    configs: []                 
    activeProfiles:                                     
    - name: development                               
      activatedBy: [development]
    - name: production                               
      activatedBy: [production]
    - name: local-production
      activatedBy: [local-production]    

profiles:
  - name: development
    manifests:
      kustomize:
        paths:
        - ./k8s/overlays/dev # rely on local containers built by skaffold

  - name: production
    manifests:
      kustomize:
        paths:
        - ./k8s/overlays/prod