apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: ory-keto-db

deploy:
  kubectl: {}
  statusCheck: true

profiles:

- name: development

  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@ory-keto-db development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@ory-keto-db development"]
              dir: .

- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@ory-keto-db production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@ory-keto-db production"]
              dir: .
