apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
- ../components/namespace

configMapGenerator:
  - name: properties-map-webhook-handler
    env: .properties

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: webhook-handler
        
      spec:
        template:
          spec:
            containers:
            - name: webhook-handler
              imagePullPolicy: Never

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: webhook-handler

      spec:
        replicas: 1
