apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: cilium-gateway

requires:
  - path: .
    configs: [cilium-gateway-generic]
    # activeProfiles:                                     
    #   - name: development
    #     activatedBy: [dev-env]
    #   - name: production                               
    #     activatedBy: [prod-env]

profiles:
  - name: dev-env
  - name: prod-env

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: cilium-gateway-generic

deploy:
  kubectl: {}
  statusCheck: true

profiles:

- name: dev-env
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

- name: prod-env
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
