apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/namespace
  - ../../components/remove-test-listner
  - ../../components/tls-certificate/staging
