apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/namespace
  # - ../../components/remove-test-listner
  # - ../../components/tls-certificate/staging-valid-tld # cannot be used for .local domains
  - ../../components/tls-certificate/dev
  - ../../components/nginx-gateway
