apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# namespace: api-data # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: api-data
    unsetOnly: true
