apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/tag-version
  - ../../components/namespace
  - ../../components/secret
  - ../../components/domain

configMapGenerator:
  - name: properties-map-auth-ui
    namespace: auth
    env: .properties

  - name: auth-ory-stack-domain
    literals:
      - auth=auth.wosoom.com

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-ui
        
      spec:
        template:
          spec:
            containers:
            - name: auth-ui
              imagePullPolicy: Always
