apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/namespace
  - ../../components/secret

configMapGenerator:
  - name: properties-map-auth-ui
    namespace: auth
    env: .properties

images:
  - name: auth-ui
    ### automatically updated # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v1.4.0 # x-release-please-version

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-ui
        
      spec:
        template:
          spec:
            containers:
            - name: auth-ui
              imagePullPolicy: Always
