### run tests for microservice unit test and integration tests

name: webhook-handler.test

on:
  workflow_call:
    # inputs:
  workflow_dispatch:

jobs:
  test-cargo:
    strategy:
      fail-fast: false
      matrix:
        platform: [
            ### TODO: commented out to make testing faster
            # macos-latest,
            ubuntu-latest,
            # windows-latest
          ]

    defaults:
      run:
        shell: bash
        working-directory: ./service/webhook-handler

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./ -> target"

      - name: install dependency
        run: |
          chmod +x script.sh
          sudo ./script.sh install.system-dependency.kafka#docker@webhook-handler

      - name: prepare repo
        run: |
          chmod +x script.sh
          ./script.sh shared-mount-point#setup#mount-bind@webhook-handler

      - name: test rust
        run: |
          chmod +x script.sh
          ./script.sh test#ci-hook#workflow@webhook-handler
