apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-token-exchange
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: auth-token-exchange
          image: auth-token-exchange:latest
          ports:
            - containerPort: 3000
              name: http-token-ex
          # envFrom:
          #   - configMapRef:
          #       name: properties-auth-token-exchange
