apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: ory-kratos-db

requires:
  - path: .
    configs: [ory-kratos-db-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: ory-kratos-db-generic

deploy:
  kubectl: {}
  statusCheck: true

profiles:

- name: development

  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@ory-kratos-db development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@ory-kratos-db development"]
              dir: .

- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod

  deploy:
    kubectl:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@ory-kratos-db production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@ory-kratos-db production"]
              dir: .
