# manifest config for the actual app configuration
# https://www.ory.sh/docs/hydra/reference/configuration

hydra:
  config:
    # TODO: remove for production
    log:
      level: debug
      leak_sensitive_values: true

    # dsn: memory # NOTE: use for development only
    dsn: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres-hydra-postgresql:5432/hydra_db?sslmode=disable&max_conns=20&max_idle_conns=4"

    serve:
      public:
        port: 4444
        # TODO: remove for production 
        cors:
          enabled: true
          allowed_origins:
            - https://donation-app.test
      admin:
        port: 4445
        request_log:
          disable_for_health: false # can be disabled for improved performance

      cookies:
        same_site_mode: Lax

      tls:
        allow_termination_from:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16

    secrets:
      system:
        - secret_must_be_overriden # overwritten using helm --set argument
      cookie:
        - secret_must_be_overriden # overwritten using helm --set argument

    urls:
      self:
        issuer: ${AUTHORIZATION_URL}
        public: ${AUTHORIZATION_URL}
      login: ${AUTH_BASE_URL}/login
      logout: ${AUTH_BASE_URL}/logout
      consent: ${AUTH_BASE_URL}/consent # Must matche auth_ui consent endpoint
      identity_provider:
        url: http://kratos-admin
        publicUrl: http://kratos-public
      error: ${AUTH_BASE_URL}/error

    ttl:
      login_consent_request: 1h
      access_token: 1h
      refresh_token: 1h
      id_token: 1h
      auth_code: 1h

    strategies:
      access_token: jwt
      jwt:
        scope_claim: list

    # for token customization or debugging
    oauth2:
      expose_internal_errors: true # TODO:remove for production
    #   token_hook: http://kratos-custom-webhook-charts.auth/add_claims

    oidc:
      subject_identifiers:
        supported_types:
          - public
        #   - pairwise
        # pairwise:
        #   salt: youReallyNeedToChangeThis
