apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - kafka-pool.yaml

components: 
- ../components/namespace

# patches:
  # - patch: |-
  #     apiVersion: kafka.strimzi.io/v1beta2
  #     kind: Kafka
  #     metadata:
  #       name: kafka-message-queue-cluster
  #   ......       
