apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: auth-ory-stack-domain
      fieldPath: data.auth
    targets:
      - select:
          kind: HTTPRoute
          name: https-auth-ui
        fieldPaths:
          - spec.hostnames.[=auth.donation-app.local]
        options:
          create: false
