apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: api-data
    newName: ghcr.io/szn-app/donation-app/api-data
    ### automatically updated
    # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v0.0.2 # x-release-please-version

# configMapGenerator:
#   - name: properties-map-api-data
#     env: config.properties

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data
        
      spec:
        template:
          spec:
            containers:
            - name: api-data
              imagePullPolicy: Always
