apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# namespace: auth # using customization transformers instead (which provides more options)
# NOTE: must be in auth namespace to access Hydra secrets
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: auth
    unsetOnly: true
