apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka-ui

requires:
  - path: ../kafka-message-queue
    configs: [kafka-message-queue]
  - path: .
    configs: [kafka-ui-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka-ui--no-dep

requires:
  - path: .
    configs: [kafka-ui-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka-ui-k8s

deploy:
  kubectl: {}
  statusCheck: true

profiles:

- name: development

  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && generate_config#predeploy-skaffold-hook@kafka-ui development"]
              dir: .

- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
      
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && generate_config#predeploy-skaffold-hook@kafka-ui production"]
              dir: .

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka-ui-generic

requires:
  - path: .
    configs: [kafka-ui-k8s]                 
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production
        activatedBy: [production]

deploy:
  helm: {}
  statusCheck: true
  
portForward:
  - resourceType: Service
    namespace: default
    resourceName: kafka-ui
    port: 80

profiles:

- name: development
  
  deploy: 
    helm:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@kafka-ui development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@kafka-ui development"]
              dir: .
      releases:
        - name: kafka-ui
          remoteChart: kafka-ui/kafka-ui
          namespace: default
          createNamespace: true
          valuesFiles:
            - config/values.yaml.local

- name: production

  deploy: 
    helm:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@kafka-ui production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@kafka-ui production"]
              dir: .
        
      releases:
        - name: kafka-ui
          remoteChart: kafka-ui/kafka-ui
          namespace: default
          createNamespace: true
          valuesFiles:
            - config/values.yaml.local