apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: auth-token-exchange

requires:
  - path: .
    configs: [auth-token-exchange-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: auth-token-exchange-generic

requires:
  - path: ../auth-ory-stack
    configs: [auth-ory-stack]                 

build:
  local: 
    push: false
    useBuildkit: true
  tagPolicy:
    sha256: {} 

deploy:
  kubectl: {}
  statusCheck: true
  
portForward:
  - resourceType: Service
    resourceName: auth-token-exchange
    namespace: auth
    port: 80

profiles:

- name: development
  # activation:
  #   - kubeContext: minikube
      
  build: 
    artifacts:
    - image: auth-token-exchange
      context: .
      docker:
        target: development
        dockerfile: Dockerfile
        buildArgs: {}
      # NOTE: limitations https://skaffold.dev/docs/filesync/#limitations
      sync:
        manual:
        - src: "src/**/*.rs"
          dest: .
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy_hook@auth-token-exchange development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy_hook@auth-token-exchange development"]
              dir: .

- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy_hook@auth-token-exchange production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy_hook@auth-token-exchange production"]
              dir: .
