apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: auth-token-exchange

requires:
  - path: .
    configs: [auth-token-exchange-generic]
    activeProfiles:
      - name: dev-env
        activatedBy: [dev-watch, dev-rebuild]
      - name: staging-env
        activatedBy: [staging-rebuild, staging-prebuilt]
      - name: prod-env
        activatedBy: [prod]
      - name: watch
        activatedBy: [dev-watch]
      - name: rebuild-debug
        activatedBy: [dev-rebuild]
      - name: rebuild-release
        activatedBy: [staging-rebuild]
      - name: prebuilt
        activatedBy: [staging-prebuilt, prod]

profiles:
  - name: dev-watch
  - name: dev-rebuild
  - name: staging-rebuild
  - name: staging-prebuilt
  - name: prod

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: auth-token-exchange-generic

# requires:
#   - path: ../../platform/scaffold
#     configs: [scaffold]

build:
  local:
    useBuildkit: true
    push: false
    tryImportMissing: false
  tagPolicy:
    sha256: {}

deploy:
  kubectl: {}
  statusCheck: true

portForward:
  - resourceType: Service
    resourceName: auth-token-exchange
    namespace: auth
    port: 80

profiles:
  - name: dev-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/dev

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy_hook@auth-token-exchange dev",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy_hook@auth-token-exchange dev",
                  ]
                dir: .

  - name: staging-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/staging

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy_hook@auth-token-exchange staging",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy_hook@auth-token-exchange staging",
                  ]
                dir: .

  - name: prod-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy_hook@auth-token-exchange prod",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy_hook@auth-token-exchange prod",
                  ]
                dir: .

  - name: watch
    build:
      artifacts:
        - image: ghcr.io/szn-app/donation-app/auth-token-exchange
          context: .
          docker:
            target: debug
            dockerfile: Dockerfile
            buildArgs: {}
          # NOTE: limitations https://skaffold.dev/docs/filesync/#limitations
          sync:
            manual:
              - src: "src/**/*.rs"
                dest: .

  - name: rebuild-debug

    build:
      artifacts:
        - image: ghcr.io/szn-app/donation-app/auth-token-exchange
          context: .
          docker:
            target: debug
            dockerfile: Dockerfile
            noCache: false
            buildArgs: {}

  - name: rebuild-release

    build:
      artifacts:
        - image: ghcr.io/szn-app/donation-app/auth-token-exchange
          context: .
          docker:
            target: release
            dockerfile: Dockerfile
            noCache: false
            buildArgs: {}

  - name: prebuilt
    build: {}
