apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auth-token-exchange

requires:
  - path: ../auth-ory-stack
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production]

build:
  local: 
    push: false
  tagPolicy:
    sha256: {} 

deploy:
  kubectl: {}
  statusCheck: true
  
portForward:
  - resourceType: Service
    resourceName: auth-token-exchange
    namespace: auth
    port: 80

profiles:

- name: development
  # activation:
  #   - kubeContext: minikube
      
  build: 
    local: {}
    artifacts:
    - image: auth-token-exchange
      context: .
      docker:
        target: development
        dockerfile: Dockerfile
        buildArgs: {}
      # NOTE: limitations https://skaffold.dev/docs/filesync/#limitations
      sync:
        manual:
        - src: "src/**/*.rs"
          dest: .
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && prehook_auth_token_exchange development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && posthook_auth_token_exchange development"]
              dir: .

- name: local-production

  build: 
    local: {}
    artifacts:
    - image: auth-token-exchange
      context: .
      docker:
        target: production
        dockerfile: Dockerfile
        buildArgs: {}
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && prehook_auth_token_exchange development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && posthook_auth_token_exchange development"]
              dir: .

- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && prehook_auth_token_exchange production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && posthook_auth_token_exchange production"]
              dir: .
