apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/namespace
  - ../../components/domain
  - ../../components/remove-test-listner
  - ../../components/tls-certificate/prod

configMapGenerator:
  - name: app-cilium-domain-config
    literals:
      - root=wosoom.com
      - api=api.wosoom.com
      - auth=auth.wosoom.com
      - longhorn=longhorn.k8s.wosoom.com
      - dashboard=dashboard.k8s.wosoom.com
      - hubble=hubble.k8s.wosoom.com
      - ory_admin=ory-admin.k8s.wosoom.com
      - minio=minio.k8s.wosoom.com
      - pgadmin4=pgadmin4.k8s.wosoom.com
      - kafka=kafka.k8s.wosoom.com
