apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - ../../base

components:
  - ../../components/namespace

secretGenerator:
  - name: keto--postgresql-credentials-user
    env: user.env.development
    behavior: merge

  - name: keto--postgresql-credentials-superuser
    env: superuser.env.development
    behavior: merge

patches:
  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: keto--cluster-db
        
      spec:
        instances: 1

  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: keto--cluster-db
        
      spec:
        superuserSecret: 
          name: keto--postgresql-credentials-superuser
