apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka-message-queue

requires:
  - path: .
    configs: [kafka-message-queue-generic]
    activeProfiles:
      - name: dev-env
        activatedBy: [dev-watch, dev-rebuild]
      - name: staging-env
        activatedBy: [staging-rebuild, staging-prebuilt]
      - name: prod-env
        activatedBy: [prod]
      - name: watch
        activatedBy: [dev-watch]
      - name: rebuild-debug
        activatedBy: [dev-rebuild]
      - name: rebuild-release
        activatedBy: [staging-rebuild]
      - name: prebuilt
        activatedBy: [staging-prebuilt, prod]

profiles:
  - name: dev-watch
  - name: dev-rebuild
  - name: staging-rebuild
  - name: staging-prebuilt
  - name: prod

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka-message-queue-generic

deploy:
  kubectl: {}
  statusCheck: true

portForward:
  - resourceType: Service
    namespace: kafka-message-queue
    resourceName: kafka-message-queue-cluster-kafka-bootstrap
    port: tcp-http

profiles:
  - name: dev-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/dev

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy-skaffold-hook@kafka-message-queue dev",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy-skaffold-hook@kafka-message-queue dev",
                  ]
                dir: .

  - name: staging-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/staging

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy-skaffold-hook@kafka-message-queue staging",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy-skaffold-hook@kafka-message-queue staging",
                  ]
                dir: .

  - name: prod-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#predeploy-skaffold-hook@kafka-message-queue prod",
                  ]
                dir: .
          after:
            - host:
                command:
                  [
                    "bash",
                    "-it",
                    "-c",
                    "source ./script.sh && func#postdeploy-skaffold-hook@kafka-message-queue prod",
                  ]
                dir: .

  - name: watch
  - name: rebuild-debug
  - name: rebuild-release
  - name: prebuilt
