apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: ory-hydra

requires:
  - path: .
    configs: [ory-hydra-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: ory-hydra-generic

requires: 
  - path: ../ory-hydra-db
    configs: [ory-hydra-db]

manifests:
  kustomize:
    paths:
    - k8s/base

deploy:
  kubectl: {}
  statusCheck: true

profiles:
- name: development
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@ory-hydra development"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@ory-hydra development"]
              dir: .

- name: production
  deploy: 
    kubectl: 
      hooks:
        before:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#predeploy_hook@ory-hydra production"]
              dir: .
        after:
          - host:
              command: ["bash", "-c", "source ./script/deploy.sh && func#postdeploy_hook@ory-hydra production"]
              dir: .