apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../../gateway/production
  - ../../web_server/production
  - ../../auth_ui/production
  - ../../auth-ory-admin-ui
