apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-data
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: api-data
          image: api-data:latest
          ports:
            - containerPort: 80
              name: api-data

          env:
            - name: POSTGRESQL_URL_RW
              valueFrom:
                configMapKeyRef:
                  name: properties-map-api-data-server
                  key: POSTGRESQL_URL_RW
                  optional: false
            - name: POSTGRESQL_URL_RO
              valueFrom:
                configMapKeyRef:
                  name: properties-map-api-data-server
                  key: POSTGRESQL_URL_RO
                  optional: false
            - name: POSTGRESQL_URL_R
              valueFrom:
                configMapKeyRef:
                  name: properties-map-api-data-server
                  key: POSTGRESQL_URL_R
                  optional: false
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-api-data-server
                  key: POSTGRESQL_USERNAME
                  optional: false
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-api-data-server
                  key: POSTGRESQL_PASSWORD
                  optional: false

          envFrom:
            - configMapRef:
                name: properties-map-api-data-server 
            - secretRef:
                name: secrets-api-data-server
