apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-token-exchange
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: auth-token-exchange
          image: ghcr.io/szn-app/donation-app/auth-token-exchange:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000
              name: auth-token-ex

          env:
          - name: HYDRA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ory-hydra-client--frontend-client
                key: client_secret
                optional: false

          # envFrom:
          # - secretRef:
          #     name: ory-hydra-client--frontend-client # implicitely

          # envFrom:
          #   - configMapRef:
          #       name: properties-auth-token-exchange

