// raw Postgres SQL parametrized queries (which tokio-postgres creates PREPARE statements from and execution)

pub mod interaction;
pub mod listing;
pub mod test;
pub mod user;

// Re-export commonly used queries for convenience
pub use interaction::message::{
    ADD_MESSAGE, GET_MESSAGES, GET_MESSAGES_BY_TRANSACTION, GET_MESSAGE_BY_ID,
};
pub use interaction::pledge::{
    ADD_PLEDGE, GET_PLEDGES, GET_PLEDGES_BY_ITEM, GET_PLEDGES_BY_PROFILE, GET_PLEDGE_BY_ID,
};
pub use interaction::review::{GET_REVIEWS, GET_REVIEW_BY_TRANSACTION_AND_SUBJECT};
pub use interaction::schedule::{ADD_SCHEDULE, GET_SCHEDULES, GET_SCHEDULE_BY_ID, UPDATE_SCHEDULE};
pub use interaction::schedule_opportunity::{
    ADD_SCHEDULE_OPPORTUNITY, GET_SCHEDULE_OPPORTUNITIES, GET_SCHEDULE_OPPORTUNITY_BY_ID,
    UPDATE_SCHEDULE_OPPORTUNITY,
};
pub use interaction::transaction::{
    ADD_TRANSACTION, GET_TRANSACTIONS, GET_TRANSACTIONS_BY_PLEDGE, GET_TRANSACTION_BY_ID,
    UPDATE_TRANSACTION,
};
pub use listing::category::{ADD_CATEGORY, GET_CATEGORIES, GET_CATEGORY_BY_ID, UPDATE_CATEGORY};
pub use listing::collection::{
    ADD_COLLECTION, GET_COLLECTIONS, GET_COLLECTIONS_BY_PROFILE, GET_COLLECTION_BY_ID,
    UPDATE_COLLECTION,
};
pub use listing::item::{GET_ITEMS, GET_ITEM_BY_ID};
pub use listing::location::{ADD_LOCATION, GET_LOCATIONS, GET_LOCATION_BY_ID, UPDATE_LOCATION};
pub use listing::media::{ADD_MEDIA, DELETE_MEDIA, GET_MEDIA, GET_MEDIA_BY_ID, GET_MEDIA_BY_ITEM};
pub use listing::publish::{
    ADD_PUBLISH, DELETE_PUBLISH, GET_PUBLISHES, GET_PUBLISHES_BY_COLLECTION, GET_PUBLISHES_BY_ITEM,
    GET_PUBLISH_BY_ITEM_AND_COLLECTION, UPDATE_PUBLISH,
};
pub use test::test::GET_TESTS;
pub use user::account::{ADD_ACCOUNT, GET_ACCOUNTS, GET_ACCOUNT_BY_ID};
pub use user::committee::{
    ADD_COMMITTEE, DELETE_COMMITTEE, GET_COMMITTEES, GET_COMMITTEES_BY_COMMUNITY,
    GET_COMMITTEES_BY_PROFILE, GET_COMMITTEE_BY_PROFILE_AND_COMMUNITY, UPDATE_COMMITTEE_ROLE,
};
pub use user::community::{ADD_COMMUNITY, GET_COMMUNITIES, GET_COMMUNITY_BY_ID, UPDATE_COMMUNITY};
pub use user::profile::{ADD_PROFILE, GET_PROFILES, GET_PROFILE_BY_ID, UPDATE_PROFILE};
