apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namespace: api-data # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: api-data
    unsetOnly: true

images:
  - name: api-data
    newName: ghcr.io/szn-app/donation-app/api-data
    ### automatically updated
    # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v0.0.2 # x-release-please-version

configMapGenerator:
  - name: properties-map-api-data-server
    env: config/.properties

secretGenerator:
  - name: secrets-api-data-server
    env: config/.env.local

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-data
        
      spec:
        template:
          spec:
            containers:
            - name: api-data
              imagePullPolicy: Always

  - target:
      kind: HTTPRoute
      name: https-api-data
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "api.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-api-data
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "api.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-api-data-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "api.wosoom.com"
