apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - kafka-pool.yaml

components:
  - ../../components/namespace

patches:
  - target:
      kind: Kafka
      name: kafka-message-queue-cluster
    patch: |
      - op: replace
        path: /spec/kafka/config/default.replication.factor
        value: 1
      - op: replace
        path: /spec/kafka/config/min.insync.replicas
        value: 1
