apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: app-kafka-ui-domain-config
  literals:
    - kafka=kafka.k8s.wosoom.com

replacements:
  - source:
      kind: ConfigMap
      name: app-kafka-ui-domain-config
      fieldPath: data.kafka
    targets:
      - select:
          kind: HTTPRoute
          name: https-k8s-kafka
        fieldPaths:
          - spec.hostnames.[=kafka.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: internal-k8s-kafka
        fieldPaths:
          - spec.hostnames.[=kafka.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
      - select:
          kind: HTTPRoute
          name: http-k8s-kafka-redirect
        fieldPaths:
          - spec.hostnames.[=kafka.k8s.donation-app.local] # note: quotes are an exaact match, otherwise it will match substring
