apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - ../../base

# namespace: auth # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: auth
    unsetOnly: true

configurations:
  - name-reference.kustomize-config.yaml 

secretGenerator:
  - name: hydra--postgresql-credentials-user
    type: kubernetes.io/basic-auth
    env: user.env.local
    behavior: merge
