apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- deployment.yml
- service.yml

# [BUG in Kustomize https://github.com/kubernetes-sigs/kustomize/issues/5047] specifiying namespace ruins configMapGenerator name resolution
# namespace: donation-app

nameSuffix: -v1
# adds labels to all resources (including selector and template fields)
labels: 
  - pairs: 
      app: web-server
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: web-server
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: _ # required field but not used

      spec: 
        template:  
          spec: 
            containers:
              - name: nginx
                resources:
                  requests:
                    cpu: "10m" 
                    memory: "20Mi"
                  limits: 
                    cpu: "50m"
                    memory: "100Mi"
