import React from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../components/ui/card";
import { Button } from "../components/ui/button";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "../components/ui/tabs";
import { Alert, AlertDescription, AlertTitle } from "../components/ui/alert";
import { Loader2 } from "lucide-react";
import { useMutation } from "@tanstack/react-query";
import { request } from "graphql-request";
import { useAuthHeaders } from "@/modules/auth/useAuthHeaders";
import {
  CreateAccountDocument,
  CreateProfileDocument,
  CreateCommunityDocument,
  CreateCommitteeDocument,
  CreateCategoryDocument,
  CreateLocationDocument,
  CreateItemDocument,
  CreateMediaDocument,
  CreateCollectionDocument,
  CreatePublishDocument,
  CreateAccountMutation,
  CreateProfileMutation,
  CreateCommunityMutation,
  CreateCommitteeMutation,
  CreateCategoryMutation,
  CreateLocationMutation,
  CreateItemMutation,
  CreateMediaMutation,
  CreateCollectionMutation,
  CreatePublishMutation,
  CommunityType,
  CommitteeRole,
  ItemType,
  ItemIntentAction,
  ItemStatus,
  ItemCondition,
  CollectionType,
  MediaType,
  ProfileType,
  CollectionVisibility,
} from "@/modules/graphql/autogenerated/graphql";
import { faker } from "@faker-js/faker";

export function MockGraphqlData() {
  const [isLoading, setIsLoading] = React.useState<string | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [success, setSuccess] = React.useState<string | null>(null);
  const { headers, isAuthenticated } = useAuthHeaders();

  const addAccountMutation = useMutation({
    mutationKey: ['createAccount', isAuthenticated],
    mutationFn: async (variables: { id: string }) => {
      return await request<CreateAccountMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateAccountDocument.toString(),
        variables,
        headers,
      )
    }
  });

  const addProfileMutation = useMutation({
    mutationKey: ['createProfile', isAuthenticated],
    mutationFn: async (variables: {
      idAccount: string;
      name: string;
      description?: string;
      profileType?: ProfileType;
    }) =>
      await request<CreateProfileMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateProfileDocument.toString(),
        variables,
        headers,
      ),
  });

  const addCommunityMutation = useMutation({
    mutationKey: ['createCommunity', isAuthenticated],
    mutationFn: async (variables: {
      name: string;
      description: string;
      type: CommunityType;
      createdBy: string;
    }) =>
      await request<CreateCommunityMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateCommunityDocument.toString(),
        variables,
        headers,
      ),
  });

  const addCommitteeMutation = useMutation({
    mutationKey: ['createCommittee', isAuthenticated],
    mutationFn: async (variables: {
      idCommunity: number;
      idProfile: string;
      memberRole: CommitteeRole;
    }) =>
      await request<CreateCommitteeMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateCommitteeDocument.toString(),
        variables,
        headers,
      ),
  });

  const addCategoryMutation = useMutation({
    mutationKey: ['createCategory', isAuthenticated],
    mutationFn: async (variables: {
      description: string;
      name: string;
      parentId?: number;
    }) =>
      await request<CreateCategoryMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateCategoryDocument.toString(),
        variables,
        headers,
      ),
  });

  const addLocationMutation = useMutation({
    mutationKey: ['createLocation', isAuthenticated],
    mutationFn: async (variables: {
      address: string;
      city: string;
      country: string;
      idProfile: string;
      name: string;
      postalCode: string;
      state: string;
    }) =>
      await request<CreateLocationMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateLocationDocument.toString(),
        variables,
        headers,
      ),
  });

  const addItemMutation = useMutation({
    mutationKey: ['createItem', isAuthenticated],
    mutationFn: async (variables: {
      title: string;
      description: string;
      idCategory: number;
      idProfile: string;
      idLocation?: number;
      price?: number;
      currency?: string;
      itemType: ItemType;
      intentAction: ItemIntentAction;
      status: ItemStatus;
      condition: ItemCondition;
    }) =>
      await request<CreateItemMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateItemDocument.toString(),
        variables,
        headers,
      ),
  });

  const addMediaMutation = useMutation({
    mutationKey: ['createMedia', isAuthenticated],
    mutationFn: async (variables: {
      idItem: number;
      url: string;
      mediaType: MediaType;
      position: number;
    }) =>
      await request<CreateMediaMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateMediaDocument.toString(),
        variables,
        headers,
      ),
  });

  const addCollectionMutation = useMutation({
    mutationKey: ['createCollection', isAuthenticated],
    mutationFn: async (variables: {
      idCommunity: number;
      title: string;
      visibility: CollectionVisibility;
      type: CollectionType;
      position: number;
    }) =>
      await request<CreateCollectionMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreateCollectionDocument.toString(),
        variables,
        headers,
      ),
  });

  const addPublishMutation = useMutation({
    mutationKey: ['createPublish', isAuthenticated],
    mutationFn: async (variables: {
      createdBy: string;
      idCollection: number;
      idItem: number;
      note?: string;
      position: number;
    }) =>
      await request<CreatePublishMutation>(
        import.meta.env.VITE_GRAPHQL_ENDPOINT,
        CreatePublishDocument.toString(),
        variables,
        headers,
      ),
  });

  const handleGenerate = async (type: string) => {
    setIsLoading(type);
    setError(null);
    setSuccess(null);

    try {
      switch (type) {
        case "accounts": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          break;
        }
        case "profiles": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
            description: faker.lorem.paragraph(),
            profileType: ProfileType.Individual,
          });
          break;
        }
        case "communities": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
          });
          const community = await addCommunityMutation.mutateAsync({
            name: faker.company.name(),
            description: faker.lorem.paragraph(),
            type: CommunityType.Organized,
            createdBy: accountId,
          });
          await addCommitteeMutation.mutateAsync({
            idCommunity: community.createCommunity.id,
            idProfile: accountId,
            memberRole: CommitteeRole.Member,
          });
          break;
        }
        case "committees": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
          });
          const community = await addCommunityMutation.mutateAsync({
            name: faker.company.name(),
            description: faker.lorem.paragraph(),
            type: CommunityType.Organized,
            createdBy: accountId,
          });
          await addCommitteeMutation.mutateAsync({
            idCommunity: community.createCommunity.id,
            idProfile: accountId,
            memberRole: CommitteeRole.Member,
          });
          break;
        }
        case "categories": {
          await addCategoryMutation.mutateAsync({
            description: faker.lorem.sentence(),
            name: faker.commerce.department(),
          });
          break;
        }
        case "locations": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
          });
          await addLocationMutation.mutateAsync({
            address: faker.location.streetAddress(),
            city: faker.location.city(),
            country: faker.location.country(),
            idProfile: accountId,
            name: faker.location.streetAddress(),
            postalCode: faker.location.zipCode(),
            state: faker.location.state(),
          });
          break;
        }
        case "items": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
          });
          const category = await addCategoryMutation.mutateAsync({
            description: faker.lorem.sentence(),
            name: faker.commerce.department(),
          });
          const location = await addLocationMutation.mutateAsync({
            address: faker.location.streetAddress(),
            city: faker.location.city(),
            country: faker.location.country(),
            idProfile: accountId,
            name: faker.location.streetAddress(),
            postalCode: faker.location.zipCode(),
            state: faker.location.state(),
          });
          await addItemMutation.mutateAsync({
            title: faker.commerce.productName(),
            description: faker.lorem.paragraph(),
            idCategory: category.createCategory.id,
            idProfile: accountId,
            idLocation: location.createLocation.id,
            itemType: ItemType.Inkind,
            intentAction: ItemIntentAction.Offer,
            status: ItemStatus.Active,
            condition: ItemCondition.BrandNew,
          });
          break;
        }
        case "media": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
          });
          const category = await addCategoryMutation.mutateAsync({
            description: faker.lorem.sentence(),
            name: faker.commerce.department(),
          });
          const location = await addLocationMutation.mutateAsync({
            address: faker.location.streetAddress(),
            city: faker.location.city(),
            country: faker.location.country(),
            idProfile: accountId,
            name: faker.location.streetAddress(),
            postalCode: faker.location.zipCode(),
            state: faker.location.state(),
          });
          const item = await addItemMutation.mutateAsync({
            title: faker.commerce.productName(),
            description: faker.lorem.paragraph(),
            idCategory: category.createCategory.id,
            idProfile: accountId,
            idLocation: location.createLocation.id,
            itemType: ItemType.Inkind,
            intentAction: ItemIntentAction.Offer,
            status: ItemStatus.Active,
            condition: ItemCondition.BrandNew,
          });
          await addMediaMutation.mutateAsync({
            idItem: item.createItem.id,
            url: faker.image.url(),
            mediaType: MediaType.Image,
            position: 1,
          });
          break;
        }
        case "collections": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
          });
          const community = await addCommunityMutation.mutateAsync({
            name: faker.company.name(),
            description: faker.lorem.paragraph(),
            type: CommunityType.Organized,
            createdBy: accountId,
          });
          const collection = await addCollectionMutation.mutateAsync({
            idCommunity: community.createCommunity.id,
            title: faker.commerce.productName(),
            visibility: CollectionVisibility.Public,
            type: CollectionType.Regular,
            position: faker.number.int({ min: 1, max: 100 }),
          });
          break;
        }
        case "publishes": {
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
          });
          const community = await addCommunityMutation.mutateAsync({
            name: faker.company.name(),
            description: faker.lorem.paragraph(),
            type: CommunityType.Organized,
            createdBy: accountId,
          });
          const collection = await addCollectionMutation.mutateAsync({
            idCommunity: community.createCommunity.id,
            title: faker.commerce.productName(),
            visibility: CollectionVisibility.Public,
            type: CollectionType.Regular,
            position: faker.number.int({ min: 1, max: 100 }),
          });
          const category = await addCategoryMutation.mutateAsync({
            description: faker.lorem.sentence(),
            name: faker.commerce.department(),
          });
          const location = await addLocationMutation.mutateAsync({
            address: faker.location.streetAddress(),
            city: faker.location.city(),
            country: faker.location.country(),
            idProfile: accountId,
            name: faker.location.streetAddress(),
            postalCode: faker.location.zipCode(),
            state: faker.location.state(),
          });
          const item = await addItemMutation.mutateAsync({
            title: faker.commerce.productName(),
            description: faker.lorem.paragraph(),
            idCategory: category.createCategory.id,
            idProfile: accountId,
            idLocation: location.createLocation.id,
            itemType: ItemType.Inkind,
            intentAction: ItemIntentAction.Offer,
            status: ItemStatus.Active,
            condition: ItemCondition.BrandNew,
          });
          await addPublishMutation.mutateAsync({
            createdBy: accountId,
            idCollection: collection.createCollection.id,
            idItem: item.createItem.id,
            note: faker.lorem.sentence(),
            position: 1,
          });
          break;
        }
        case "all": {
          // Generate accounts and profiles
          const accountId = faker.string.uuid();
          await addAccountMutation.mutateAsync({ id: accountId });
          const profile = await addProfileMutation.mutateAsync({
            idAccount: accountId,
            name: faker.person.fullName(),
            description: faker.lorem.paragraph(),
            profileType: ProfileType.Individual,
          });

          // Generate community and committee
          const community = await addCommunityMutation.mutateAsync({
            name: faker.company.name(),
            description: faker.lorem.paragraph(),
            type: CommunityType.Organized,
            createdBy: accountId,
          });
          await addCommitteeMutation.mutateAsync({
            idCommunity: community.createCommunity.id,
            idProfile: accountId,
            memberRole: CommitteeRole.Member,
          });

          // Generate category and location
          const category = await addCategoryMutation.mutateAsync({
            description: faker.lorem.sentence(),
            name: faker.commerce.department(),
          });
          const location = await addLocationMutation.mutateAsync({
            address: faker.location.streetAddress(),
            city: faker.location.city(),
            country: faker.location.country(),
            idProfile: accountId,
            name: faker.location.streetAddress(),
            postalCode: faker.location.zipCode(),
            state: faker.location.state(),
          });

          // Generate item and media
          const item = await addItemMutation.mutateAsync({
            title: faker.commerce.productName(),
            description: faker.lorem.paragraph(),
            idCategory: category.createCategory.id,
            idProfile: accountId,
            idLocation: location.createLocation.id,
            itemType: ItemType.Inkind,
            intentAction: ItemIntentAction.Offer,
            status: ItemStatus.Active,
            condition: ItemCondition.BrandNew,
          });
          await addMediaMutation.mutateAsync({
            idItem: item.createItem.id,
            url: faker.image.url(),
            mediaType: MediaType.Image,
            position: 1,
          });

          // Generate collection and publish
          const collection = await addCollectionMutation.mutateAsync({
            idCommunity: community.createCommunity.id,
            title: faker.commerce.productName(),
            visibility: CollectionVisibility.Public,
            type: CollectionType.Regular,
            position: faker.number.int({ min: 1, max: 100 }),
          });
          await addPublishMutation.mutateAsync({
            createdBy: accountId,
            idCollection: collection.createCollection.id,
            idItem: item.createItem.id,
            note: faker.lorem.sentence(),
            position: 1,
          });
          break;
        }
        default:
          throw new Error(`Unknown data type: ${type}`);
      }
      setSuccess(`Successfully generated ${type} data`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
    } finally {
      setIsLoading(null);
    }
  };

  const handleClear = async () => {
    setIsLoading("clear");
    setError(null);
    setSuccess(null);

    try {
      // Clear all data by generating a new account and using it to clear related data
      const accountId = faker.string.uuid();
      await addAccountMutation.mutateAsync({ id: accountId });

      // Clear profiles
      await addProfileMutation.mutateAsync({
        idAccount: accountId,
        name: "CLEAR",
        description: "CLEAR",
      });

      // Clear communities
      await addCommunityMutation.mutateAsync({
        name: "CLEAR",
        description: "CLEAR",
        type: CommunityType.Organized,
        createdBy: accountId,
      });

      // Clear categories
      await addCategoryMutation.mutateAsync({
        description: "CLEAR",
        name: "CLEAR",
      });

      // Clear locations
      await addLocationMutation.mutateAsync({
        address: "CLEAR",
        city: "CLEAR",
        country: "CLEAR",
        idProfile: accountId,
        name: "CLEAR",
        postalCode: "CLEAR",
        state: "CLEAR",
      });

      // Clear items
      const category = await addCategoryMutation.mutateAsync({
        description: "CLEAR",
        name: "CLEAR",
      });
      const location = await addLocationMutation.mutateAsync({
        address: "CLEAR",
        city: "CLEAR",
        country: "CLEAR",
        idProfile: accountId,
        name: "CLEAR",
        postalCode: "CLEAR",
        state: "CLEAR",
      });
      await addItemMutation.mutateAsync({
        title: "CLEAR",
        description: "CLEAR",
        idCategory: category.createCategory.id,
        idProfile: accountId,
        idLocation: location.createLocation.id,
        itemType: ItemType.Inkind,
        intentAction: ItemIntentAction.Offer,
        status: ItemStatus.Active,
        condition: ItemCondition.BrandNew,
      });

      // Clear collections
      await addCollectionMutation.mutateAsync({
        idCommunity: 0,
        title: "CLEAR",
        visibility: CollectionVisibility.Restricted,
        type: CollectionType.Regular,
        position: 0,
      });

      setSuccess("Successfully cleared all data");
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
    } finally {
      setIsLoading(null);
    }
  };

  return (
    <div className="container mx-auto p-6">
      <h1 className="mb-6 text-3xl font-bold">GraphQL Mock Data Generator</h1>

      {error && (
        <Alert variant="destructive" className="mb-4">
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {success && (
        <Alert className="mb-4">
          <AlertTitle>Success</AlertTitle>
          <AlertDescription>{success}</AlertDescription>
        </Alert>
      )}

      <Tabs defaultValue="accounts" className="w-full">
        <TabsList className="grid w-full grid-cols-5">
          <TabsTrigger value="accounts">Accounts</TabsTrigger>
          <TabsTrigger value="communities">Communities</TabsTrigger>
          <TabsTrigger value="items">Items</TabsTrigger>
          <TabsTrigger value="collections">Collections</TabsTrigger>
          <TabsTrigger value="all">All Data</TabsTrigger>
        </TabsList>

        <TabsContent value="accounts">
          <Card>
            <CardHeader>
              <CardTitle>Account & Profile Data</CardTitle>
              <CardDescription>
                Generate mock accounts and profiles
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Button
                  onClick={() => handleGenerate("accounts")}
                  disabled={isLoading === "accounts"}
                >
                  {isLoading === "accounts" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Accounts
                </Button>
                <Button
                  onClick={() => handleGenerate("profiles")}
                  disabled={isLoading === "profiles"}
                >
                  {isLoading === "profiles" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Profiles
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="communities">
          <Card>
            <CardHeader>
              <CardTitle>Community Data</CardTitle>
              <CardDescription>
                Generate mock communities and committees
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Button
                  onClick={() => handleGenerate("communities")}
                  disabled={isLoading === "communities"}
                >
                  {isLoading === "communities" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Communities
                </Button>
                <Button
                  onClick={() => handleGenerate("committees")}
                  disabled={isLoading === "committees"}
                >
                  {isLoading === "committees" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Committees
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="items">
          <Card>
            <CardHeader>
              <CardTitle>Item Data</CardTitle>
              <CardDescription>
                Generate mock items, categories, and locations
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Button
                  onClick={() => handleGenerate("categories")}
                  disabled={isLoading === "categories"}
                >
                  {isLoading === "categories" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Categories
                </Button>
                <Button
                  onClick={() => handleGenerate("locations")}
                  disabled={isLoading === "locations"}
                >
                  {isLoading === "locations" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Locations
                </Button>
                <Button
                  onClick={() => handleGenerate("items")}
                  disabled={isLoading === "items"}
                >
                  {isLoading === "items" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Items
                </Button>
                <Button
                  onClick={() => handleGenerate("media")}
                  disabled={isLoading === "media"}
                >
                  {isLoading === "media" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Media
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="collections">
          <Card>
            <CardHeader>
              <CardTitle>Collection Data</CardTitle>
              <CardDescription>
                Generate mock collections and publishes
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Button
                  onClick={() => handleGenerate("collections")}
                  disabled={isLoading === "collections"}
                >
                  {isLoading === "collections" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Collections
                </Button>
                <Button
                  onClick={() => handleGenerate("publishes")}
                  disabled={isLoading === "publishes"}
                >
                  {isLoading === "publishes" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate Publishes
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="all">
          <Card>
            <CardHeader>
              <CardTitle>Generate All Data</CardTitle>
              <CardDescription>
                Generate all mock data in the correct order
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Button
                  onClick={() => handleGenerate("all")}
                  disabled={isLoading === "all"}
                >
                  {isLoading === "all" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Generate All Data
                </Button>
                <Button
                  variant="destructive"
                  onClick={handleClear}
                  disabled={isLoading === "clear"}
                >
                  {isLoading === "clear" && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Clear All Data
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
