apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yml
  - ../../base
  - service.yml

# namespace: auth # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: auth
    unsetOnly: true

secretGenerator:
  - name: hydra--postgresql-credentials-user
    env: config/user.env.development
    behavior: merge

  - name: hydra--postgresql-credentials-superuser
    env: config/superuser.env.development
    behavior: merge

patches:

  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: hydra--cluster
        
      spec:
        instances: 1

  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: hydra--cluster
        
      spec:
        superuserSecret: 
          name: hydra--postgresql-credentials-superuser
