apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: kafka-message-queue-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: longhorn-local-ext4-1replica
        # size: 10Gi
        size: 1Gi
        kraftMetadata: shared
        # NOTE: Kafka Strimzi generates cluster id  which is not configurable and must match existing volume; thus attaching to existing volume fails.
        deleteClaim: true    
        
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: kafka-message-queue-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: longhorn-network-xfs-1replica # xfs optimized for sequential writes; suboptimal: network mounted storage adds latency;
        # size: 10Gi
        size: 1Gi
        kraftMetadata: shared
        # NOTE: Kafka Strimzi generates cluster id  which is not configurable and must match existing volume; thus attaching to existing volume fails.
        deleteClaim: true

