apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: auth-ory-admin-ui

requires:
  - path: .
    configs: [auth-ory-admin-ui-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: auth-ory-admin-ui-generic

requires:
  - path: ../auth-ory-stack
    configs: [auth-ory-stack]                 

deploy:
  kubectl: {}
  statusCheck: false

profiles:

- name: development
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

- name: production
  manifests:
    kustomize:
      paths:
      # fix issue probably with exceeded resources usage causing kubernetes node failure
      - k8s/overlays/dummy
