apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auth-ory-admin-ui

requires:
  - path: ../auth-ory-stack
    configs: []                 
    activeProfiles:                                     
     - name: development                               
       activatedBy: [development, local-production]
     - name: production                               
       activatedBy: [production] 

deploy:
  kubectl: {}
  statusCheck: false

profiles:

- name: development
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev

- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
