apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/namespace
  - ../../components/secret

configMapGenerator:
  - name: properties-map-auth-ui
    namespace: auth
    env: .properties
