apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: api-data-object-store

requires:
  - path: .
    configs: [api-data-object-store-generic]
    activeProfiles:                                     
      - name: development
        activatedBy: [development, local-production]
      - name: production                               
        activatedBy: [production]

profiles:
  - name: development
  - name: local-production
  - name: production

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: api-data-object-store-generic

deploy:
  # https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant-helm.html#deploy-tenant-helm
  # https://min.io/docs/minio/kubernetes/upstream/reference/tenant-chart-values.html
  helm: {}
  kubectl: {}
  statusCheck: true
  
portForward:
  - resourceType: Service
    namespace: api-data
    resourceName: minio-object-store-console
    port: 9090

profiles:

- name: development

  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
  
  deploy: 
    helm:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@api-data-object-store development"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@api-data-object-store development"]
              dir: .
        
      releases:
        - name: minio-object-store
          remoteChart: minio-operator/tenant
          namespace: api-data
          createNamespace: true
          valuesFiles:
            - minio-tenant-values.yaml
            - values.dev.yaml      

- name: production

  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod

  deploy: 
    helm:
      hooks:
        before:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#predeploy-skaffold-hook@api-data-object-store production"]
              dir: .
        after:
          - host:
              command: ["bash", "-it", "-c", "source ./script/deploy.sh && func#postdeploy-skaffold-hook@api-data-object-store production"]
              dir: .
        
      releases:
        - name: minio-object-store
          remoteChart: minio-operator/tenant
          namespace: api-data
          createNamespace: true
          valuesFiles:
            - minio-tenant-values.yaml
            - config/values.prod.yaml.local
