apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: api-data-server
    ### automatically updated
    # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v0.1.7 # x-release-please-version
