apiVersion: v1
kind: Service

metadata:
  name: api-data-server
spec:
  type: ClusterIP
  ports:
    - name: service-api-data-http
      port: 80
      targetPort: api-data-http
    - name: service-api-data-grpc
      port: 50051
      targetPort: api-data-grpc
