apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
  - ../../route
  
# namePrefix: prod-
# nameSuffix: -v1

configurations:
  - ./name-reference.kustomize-config.yml
