oathkeeper:
  config:
    log:
      level: debug
      format: json

    serve:
      proxy:
        port: 4455
      api:
        port: 4456
      prometheus:
        port: 9000

    access_rules:
      matching_strategy: regexp
      repositories:
        - file:///etc/rules/access-rules.json

    authenticators:
      jwt:
        enabled: true
        config:
          jwks_urls:
            - https://hydra-public/.well-known/jwks.json
          scope_strategy: hierarchic
          jwks_max_wait: 5s
      anonymous:
        enabled: true
        config:
          subject: guest

    authorizers:
      allow:
        enabled: true
      deny:
        enabled: true

    # https://www.ory.sh/docs/oathkeeper/pipeline/mutator
    mutators:
      header:
        enabled: true
        config:
          headers:
            X-User: "{{ print .Subject }}"
      noop:
        enabled: true
      # id_token:
      #   enabled: true
      #   config:
      #     issuer_url: http://hydra-admin/
      #     jwks_url: http://overriden_by_helm_argument/ # a jwks.json file which gets overriden by helm argument     --set-file 'oathkeeper.mutatorIdTokenJWKs=./path/to/jwks.json'

    errors:
      handlers:
        json:
          enabled: true
          config: {}
