apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  labels:
    cnpg.io/cluster: cluster-example
spec:
  instances: 3

  # https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4-5

  storage:
    size: 1Gi
