apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

  - ../../../../service/cilium-gateway/k8s/overlays/dev
  - ../../../../service/envoy-proxy/k8s/base
  
  # - ../../../../service/auth-ory-stack/k8s/overlays/dev
  # - ../../../../service/auth-ory-admin-ui/k8s/overlays/dev
  # - ../../../../service/auth-token-exchange/k8s/overlays/dev
  # - ../../../../service/auth-ui/k8s/overlays/dev
  
  # - ../../../../service/web-server/k8s/overlays/dev
  # - ../../../../service/api-data/server/k8s/overlays/dev

  - ../../route
  
# namePrefix: prod-
# nameSuffix: -v1

configurations:
  - ./name-reference.kustomize-config.yml
