apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/external-authorizer

patches:
  - target:
      kind: SecurityPolicy
      name: internal-gateway
    patch: |-
      - op: add
        path: /spec/extAuth/http/headersToBackend/-
        value: "debug-app-bypass-auth"

  - target:
      kind: SecurityPolicy
      name: internal-gateway
    patch: |-
      - op: add
        path: /spec/extAuth/http/headersToBackend/-
        value: "debug-app-user-id"
