apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: SecurityPolicy
      name: internal-gateway

    patch: |-
      - op: replace
        path: /spec/cors/allowOrigins/0
        value: "https://wosoom.com"

      - op: replace
        path: /spec/cors/allowOrigins/1
        value: "https://api.wosoom.com"