apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/namespace
  - ../../components/domain

images:
  - name: web-server
    ### automatically updated - TODO: fix and use ArgoCD or other deployment tool
    # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v0.0.86 # x-release-please-version

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-server
        
      spec:
        template:
          spec:
            containers:
            - name: web-server
              imagePullPolicy: Always

# set security context
# - patch: |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: web-server

#     spec:
#       template:
#         spec:
#           containers:
#           - name: web-server
#             securityContext:
#               runAsUser: 101 # nginx
#               runAsNonRoot: true
#               readOnlyRootFilesystem: true
#               allowPrivilegeEscalation: false

# set resource limits
# - patch: |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: web-server

#     spec:
#       template:
#         spec:
#           containers:
#           - name: web-server
#             resources:
#               limits:
#                 cpu: 50m
#                 memory: 128Mi
#               requests:
#                 cpu: 10m
#                 memory: 64Mi
