apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - ../../base

components:
  - ../../components/namespace

configurations:
  - name-reference.kustomize-config.yaml

secretGenerator:
  - name: keto--postgresql-credentials-user
    type: kubernetes.io/basic-auth
    env: user.env.local
    behavior: merge
