# manifest config for the actual app configuration
# https://www.ory.sh/docs/keto/reference/configuration

keto:
  config:
    log:
      level: debug
      format: json
      leak_sensitive_values: true

    # dsn: memory # NOTE: use for development only
    dsn: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres-keto-postgresql:5432/keto_db?sslmode=disable&max_conns=20&max_idle_conns=4"

    serve:
      read:
        port: 4466
      write:
        port: 4467
      metrics:
        port: 4468

    namespaces:
      - id: 0
        name: resources
