apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namespace: donation-app # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: donation-app
    unsetOnly: true

images:
  - name: webhook-handler
    newName: ghcr.io/szn-app/donation-app/webhook-handler
    ### automatically updated
    # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v0.0.5 # x-release-please-version

configMapGenerator:
  - name: properties-map-webhook-handler
    env: .properties

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: webhook-handler
        
      spec:
        template:
          spec:
            containers:
            - name: webhook-handler
              imagePullPolicy: Always
