apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namePrefix: prod-
# nameSuffix: -v1

components:
  - ../../components/dashboard
  - ../../components/hubble
  - ../../components/longhorn
  - ../../components/ory-stack
