# https://cloudnative-pg.io/documentation/current/image_catalog/
# define images for operators to use (any change to this file will trigger an update to all using resources in the cluster)
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
    name: postgresql-cnpg-extension--dev
    namespace: cnpg-system
spec:
    images:
    - major: 17
      image: api-data--postgresql-cnpg-extension:latest
