apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service.yml

# configMapGenerator:
#   - name: properties-map-api-data
#     env: config.properties

patches:

  # update with short down time
  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: cluster-example
        
      spec:
        instances: 1