apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-user-credentials.yml
  - ../../base
  - service.yml

# configMapGenerator:
#   - name: properties-map-api-data
#     env: config.properties

patches:

  # update with short down time
  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: cluster-app-data
        
      spec:
        instances: 1

  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: cluster-app-data
        
      spec:
        superuserSecret:
          name: dev--postgresql-superuser-credentials

  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: cluster-app-data
        
      spec:
        bootstrap: 
          initdb:
            secret:
              name: dev--postgresql-superuser-credentials