apiVersion: v1
kind: Service
metadata:
  name: dev--cluster-app-data
  # namespace: database
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: cluster-app-data