apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # remove test listeners from production
  - target:
      kind: Gateway
      name: gateway
    # remove two listeners begining from #3
    patch: |-
      - op: remove
        path: /spec/listeners/0
      - op: remove
        path: /spec/listeners/1
