# development setup with ingress to resolve dns: donation-app.local → ingress-dns → minikube ip  → ingress  → gateway

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # - ingress.yaml
  - cert-manager-cluster-issuer.yaml

components: 
- ../components/namespace

configMapGenerator:
  - name: dev-secret-config
    literals:
      - dev=dev-tls

replacements:
  - source:
      kind: ConfigMap
      name: dev-secret-config
      fieldPath: data.dev
    targets:
      - select:
          kind: Gateway
          name: gateway
        fieldPaths:
          - spec.listeners.[name=https].tls.certificateRefs.[kind=Secret].name

patches:
  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: "nginx"

### patches for tls certificateRefs
  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "selfsigned-issuer"

