apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/dashboard
  - ../../components/hubble
  - ../../components/longhorn
  - ../../components/ory-stack
  - ../../components/domain

# namePrefix: prod-
# nameSuffix: -v1

configMapGenerator:
  - name: app-scaffold-domain-config
    literals:
      - test=test.wosoom.com
      - longhorn=longhorn.k8s.wosoom.com
      - dashboard=dashboard.k8s.wosoom.com
      - hubble=hubble.k8s.wosoom.com
      - auth=auth.wosoom.com

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: "worker"
