apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: auth-ui
    ### automatically updated # FIX: release-please updater NOT WOKRING. update release-please after PR accepted https://github.com/googleapis/release-please/pull/2422
    newTag: v1.5.1 # x-release-please-version
