apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: envoy-proxy

requires:
  - path: .
    configs: [envoy-proxy-generic]
    activeProfiles:
      - name: dev-env
        activatedBy: [dev-watch, dev-rebuild]
      - name: staging-env
        activatedBy: [staging-rebuild, staging-prebuilt]
      - name: prod-env
        activatedBy: [prod]
      - name: watch
        activatedBy: [dev-watch]
      - name: rebuild-debug
        activatedBy: [dev-rebuild]
      - name: rebuild-release
        activatedBy: [staging-rebuild]
      - name: prebuilt
        activatedBy: [staging-prebuilt, prod]

profiles:
  - name: dev-watch
  - name: dev-rebuild
  - name: staging-rebuild
  - name: staging-prebuilt
  - name: prod

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: envoy-proxy-generic

deploy:
  kubectl: {}
  statusCheck: true

profiles:
  - name: dev-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/dev

  - name: staging-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/staging

  - name: prod-env
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod

  - name: watch
  - name: rebuild-debug
  - name: rebuild-release
  - name: prebuilt
