# automatically merge development PRs (features, hotfixes, etc.)

name: _test_auto

on:
  workflow_dispatch:  
      
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: merge PR
        run: |
            gh pr merge 59 --squash --auto -t "feat(dummy): message update from Rust code"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
            
            
