# automatically merge development PRs (features, hotfixes, etc.)

name: _test_auto

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    
  workflow_dispatch:  

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

    #   - name: merge PR
    #     shell: bash
    #     run: | 
    #         gh pr review --approve "https://github.com/szn-app/donation-app/pull/60"
    #         gh pr merge "https://github.com/szn-app/donation-app/pull/60" --squash --auto -t "feat(dummy): message update from Rust code"
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                      
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
            PR_URL: "https://github.com/szn-app/donation-app/pull/60"
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
            PR_URL: "https://github.com/szn-app/donation-app/pull/60"
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            
