# automatically merge development PRs (features, hotfixes, etc.)

name: _test_auto

on:
  workflow_dispatch:  

permissions: write-all

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: merge PR
        run: |
            gh pr merge 59 --squash -t "feat(dummy): message update from Rust code"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
            
            
