### run tests for microservice unit test and integration tests

name: api-data.test

on:
  pull_request:
    branches: [main]
    paths: ['service/api-data/server/**']
  workflow_dispatch: 
      
jobs:

  test-cargo:
    # release-please PR originate from branches with `release-please--branches--*`
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'automerge') || github.event_name == 'workflow_dispatch' }}

    strategy:
      fail-fast: false
      matrix:
        platform: [
          ### TODO: commented out to make testing faster
          # macos-latest, 
          ubuntu-latest, 
          # windows-latest 
        ]

    defaults:
      run:
        shell: bash
        working-directory: ./service/api-data/server

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './ -> target'

      - name: test rust
        run: cargo test
