name: monorepo-release (release-please)

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    
    outputs:
      web-server--release_created: ${{ steps.release-step.outputs['service/web-server--release_created'] }}
      web-server--tag_name: ${{ steps.release-step.outputs['service/web-server--tag_name'] }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release-step
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "debug root path outputs:"
          echo "${{ steps.release-step.outputs.release_created }}"
          echo "${{ steps.release-step.outputs.tag_name }}"
          echo "debug service/web-server path outputs:"
          echo "${{ steps.release-step.outputs['service/web-server--release_created'] }}"
          echo "${{ steps.release-step.outputs['service/web-server--tag_name'] }}"

  publish-package:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.web-server--release_created }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include: 
          - platform: "ubuntu-latest"
            args: ""
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "windows-latest"
            args: ""

    runs-on: ${{matrix.platform}}
    
    defaults:
      run:
        shell: bash
        working-directory: ./service/web-server
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # find release ID given the associated tag and pass it to Tauri build in following step (bc it seems like tauri-action fails to find the release id sometimes)
      - name: Find Release ID
        id: find_release_id
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          release_id=$(gh release view ${{ needs.release-please.outputs.web-server--tag_name }} --json id | jq -r '.id')
          echo "::set-output name=release_id::$release_id"

      - name: Install dependencies for tauri 
        if: startsWith(matrix.platform, 'ubuntu')
        working-directory: ./
        run: | 
          chmod +x ./script.sh
          ./script.sh install_tauri_dependencies_debian
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false  # Prevent automatic installation of dependencies
          version: latest
          
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: ./service/web-server

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install dependencies & build project
        working-directory: ./
        run: |
          chmod +x ./script.sh
          ./script.sh build_react_spa
        
      - name: build project (tauri app) & upload artifacts to release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          projectPath: "service/web-server"
          tagName: "${{ steps.find_release_id.outputs.release_id }}" # tag to find the release for (each github tag may be associated with a single release only)
          args: ${{ matrix.args }} # build specific formats
