name: publish package web-server

on:
  push:
    tags:
      - 'web-server-v*'
  workflow_dispatch:

jobs:
  publish-package:
    permissions:
      contents: write
      
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        service: 
          - web-server
        
    runs-on: ${{matrix.platform}}
    
    defaults:
      run:
        shell: bash
        working-directory: ./service/${{matrix.service}}
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies for tauri 
        if: matrix.platform == 'ubuntu-latest'
        run: | 
          sudo apt-get update 
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false  # Prevent automatic installation of dependencies
          version: latest
          
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: ./service/${{matrix.service}}

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install web dependencies
        run: pnpm install --frozen-lockfile

      - name: build web
        run: pnpm run build

      - name: build tauri app 
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{matrix.service}}-${{ github.ref_name }}
          releaseName: "${{matrix.service}} ${{github.ref_name}}"
          releaseBody: 'See the assets to download the app.'
          releaseDraft: false
          prerelease: false
