### monorepo release workflow using release-please tool

name: release

on:
  push:
    branches:
      - main
  workflow_dispatch: # NOTE: in this manual dispatch, the tag_name will fallback to "dummy"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      web-server--release_created: ${{ steps.release-step.outputs['service/web-server--release_created'] }}
      web-server--tag_name: ${{ steps.release-step.outputs['service/web-server--tag_name'] }}
      
      auth-ui--release_created: ${{ steps.release-step.outputs['service/auth-ui--release_created'] }}
      auth-ui--tag_name: ${{ steps.release-step.outputs['service/auth-ui--tag_name'] }}
      
      auth-token-exchange--release_created: ${{ steps.release-step.outputs['service/auth-token-exchange--release_created'] }}
      auth-token-exchange--tag_name: ${{ steps.release-step.outputs['service/auth-token-exchange--tag_name'] }}

      webhook-handler--release_created: ${{ steps.release-step.outputs['service/webhook-handler--release_created'] }}
      webhook-handler--tag_name: ${{ steps.release-step.outputs['service/webhook-handler--tag_name'] }}

      api-data--release_created: ${{ steps.release-step.outputs['service/api-data--release_created'] }}
      api-data--tag_name: ${{ steps.release-step.outputs['service/api-data--tag_name'] }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release-step
        with:
          token: ${{ secrets.PAT_WORKFLOW }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "debug root path outputs:"
          echo "${{ steps.release-step.outputs.release_created }}"
          echo "${{ steps.release-step.outputs.tag_name }}"
          
          echo "debug service/web-server path outputs:"
          echo "${{ steps.release-step.outputs['service/web-server--release_created'] }}"
          echo "${{ steps.release-step.outputs['service/web-server--tag_name'] }}"
          
          echo "debug service/auth-ui path outputs:"
          echo "${{ steps.release-step.outputs['service/auth-ui--release_created'] }}"
          echo "${{ steps.release-step.outputs['service/auth-ui--tag_name'] }}"
          
          echo "debug service/auth-token-exchange path outputs:"
          echo "${{ steps.release-step.outputs['service/auth-token-exchange--release_created'] }}"
          echo "${{ steps.release-step.outputs['service/auth-token-exchange--tag_name'] }}"

          echo "debug service/webhook-handler path outputs:"
          echo "${{ steps.release-step.outputs['service/webhook-handler--release_created'] }}"
          echo "${{ steps.release-step.outputs['service/webhook-handler--tag_name'] }}"

          echo "debug service/api-data path outputs:"
          echo "${{ steps.release-step.outputs['service/api-data--release_created'] }}"
          echo "${{ steps.release-step.outputs['service/api-data--tag_name'] }}"

  web-server:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.web-server--release_created == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/autogenerated-web-server.release.yaml
    secrets: inherit
    with: 
        tag-name: ${{ needs.release-please.outputs.web-server--tag_name || 'dummy' }}

  auth-ui: 
    needs: [release-please]
    if: ${{ needs.release-please.outputs.auth-ui--release_created || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/autogenerated-auth-ui.release.yaml
    secrets: inherit
    with: 
        tag-name: ${{ needs.release-please.outputs.auth-ui--tag_name || 'dummy' }}

  auth-token-exchange: 
    needs: [release-please]
    if: ${{ needs.release-please.outputs.auth-token-exchange--release_created || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/autogenerated-auth-token-exchange.release.yaml
    secrets: inherit
    with: 
        tag-name: ${{ needs.release-please.outputs.auth-token-exchange--tag_name || 'dummy' }}

  webhook-handler: 
    needs: [release-please]
    if: ${{ needs.release-please.outputs.webhook-handler--release_created || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/autogenerated-webhook-handler.release.yaml
    secrets: inherit
    with: 
        tag-name: ${{ needs.release-please.outputs.webhook-handler--tag_name || 'dummy' }}
  
  api-data-server:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.api-data--release_created || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/autogenerated-api-data-server.release.yaml
    secrets: inherit
    with: 
        tag-name: ${{ needs.release-please.outputs.api-data--tag_name || 'dummy' }}
