# name: tag release

# on: 
#     pull_request: 
#         types: [closed]
#         branches: [main]

# jobs: 
#     create_tag: 
#         runs-on: ubuntu-latest
#         if: github.event.pull_request.merged == true

#         defaults:
#             run:
#                 shell: bash
#                 working-directory: ./service/web-server          

#         steps:
#             - name: checkout code
#               uses: actions/checkout@v4
            
#             - name: generate tag version number 
#               id: tag_version
#               run: |
#                 serveice=web-server
#                 current_version=$(jq -r .version package.json)
#                 # bump version
#                 if [[ "${GITHUB_HEAD_REF}" == "feature/"* ]]; then
#                     new_version=$(echo "$current_version" | awk -F. '{printf "%d.%d.%d\n", $1, $2+1, $3}')
#                 elif [[ "${GITHUB_HEAD_REF}" == "hotfix/"* ]]; then
#                     new_version=$(echo "$current_version" | awk -F. '{printf "%d.%d.%d\n", $1, $2, $3+1}')
#                 else 
#                     new_version=$(echo "$current_version" | awk -F. '{printf "%d.%d.%d\n", $1, $2, $3+1}')
#                 fi
#                 # assign version variable
#                 echo "::set-output name=tag_version::$new_version"

#             - name: update package.json version 
#               run: | 
#                 new_version=${{ steps.tag_version.outputs.tag_version }} 
#                 # update package.json
#                 jq --arg new_version "$new_version" '.version = $new_version' package.json > temp.json && mv temp.json package.json
#                 # commit change
#                 git add package.json
#                 git commit -m "$service $new_version version bump"

                
#             - name: create git tag    
#               run: |
#                 git tag -a "v${{ steps.tag_version.outputs.tag_version }}" -m "web-server v${{ steps.tag_version.outputs.tag_version }}"
#                 git push origin --tags


