# https://gateway.envoyproxy.io/docs/api/extension_types/#securitypolicy
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferenceGrant
metadata:
  name: allow-envoy-gateway
  namespace: auth # backend service
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: keto-read # backend service
---
# https://gateway.envoyproxy.io/contributions/design/security-policy/
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: internal-gateway
  namespace: envoy-gateway-system # must be same as targetRefs' namesapce
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway-internal
  extAuth:
    grpc:
      backendRefs:
        - name: keto-read
          namespace: auth
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: https-api
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
      sectionName: https-api

  hostnames:
    - api.donation-app.test

  rules:
    - backendRefs:
        # kubernetees service
        - name: envoy-gateway-internal
          namespace: envoy-gateway-system
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: internal-api
  namespace: donation-app
spec:
  parentRefs:
    - name: envoy-gateway-internal
      namespace: envoy-gateway-system
      sectionName: http

  hostnames:
    - api.donation-app.test

  rules:
    - backendRefs:
        # kubernetees service
        - name: web-server
          namespace: donation-app
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: http-api-redirect
  namespace: cert-manager # HTTPRoute must be placed in same namespace as the target backend service
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
      sectionName: http-api

  hostnames:
    - "api.donation-app.test"

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

    - matches:
        - path:
            type: PathPrefix
            value: "/.well-known/"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: "/livez"
      backendRefs:
        - name: cert-manager-health-endpoint
          namespace: cert-manager
          port: 80
