apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components: 
- ../components/namespace
- ../components/domain

configMapGenerator:
  - name: api-data-object-store-domain
    literals:
      - minio=minio.k8s.wosoom.com