apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namespace: api-data # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: api-data
    unsetOnly: true

patches:
  - target:
      kind: HTTPRoute
      name: https-k8s-minio
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "minio.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: internal-k8s-minio
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "minio.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-k8s-minio-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "minio.k8s.wosoom.com"
